Repository zmkfirmware/zmk, pull requests merged in 2020-08, with the labels that each got.

#69 Improve mod-tap behaviour
  app/CMakeLists.txt
  app/Kconfig
  app/include/zmk/event-manager.h
  app/src/behaviors/behavior_key_press.c
  app/src/behaviors/behavior_mod_tap.c
  app/src/event_manager.c
  app/src/events/keycode_state_changed.c
Labels: behaviors, bug, core

#73 Refactor to using .keymap files
  app/CMakeLists.txt
  app/boards/arm/planck/planck_rev6.keymap
  app/boards/shields/clueboard_california/clueboard_california.keymap
  app/boards/shields/kyria/kyria.keymap
  app/boards/shields/lily58/lily58.keymap
  app/boards/shields/petejohanson_handwire/Kconfig.defconfig
  app/boards/shields/petejohanson_handwire/Kconfig.shield
  app/boards/shields/petejohanson_handwire/keymap/keymap.overlay
  app/boards/shields/petejohanson_handwire/petejohanson_handwire.conf
  app/boards/shields/petejohanson_handwire/petejohanson_handwire.overlay
  app/boards/shields/petejohanson_pro_micro_handwire/Kconfig.defconfig
  app/boards/shields/petejohanson_pro_micro_handwire/Kconfig.shield
  app/boards/shields/petejohanson_pro_micro_handwire/keymap/keymap.overlay
  app/boards/shields/petejohanson_pro_micro_handwire/petejohanson_pro_micro_handwire.conf
  app/boards/shields/petejohanson_pro_micro_handwire/petejohanson_pro_micro_handwire.overlay
  app/cmake/zmk_config.cmake
Labels: core, enhancement, keymaps

#83 macOS compatability fixes for setup.sh
  docs/static/setup.sh
Labels: bug, user configs

#97 fix(build): Remove more unused west modules.
  .github/workflows/build.yml
  app/west.yml
Labels: enhancement

#98 Feature: Layer toggle
  app/CMakeLists.txt
  app/dts/behaviors.dtsi
  app/dts/behaviors/toggle_layer.dtsi
  app/dts/bindings/behaviors/zmk,behavior-toggle-layer.yaml
  app/include/zmk/keymap.h
  app/src/behaviors/behavior_toggle_layer.c
  app/src/keymap.c
  docs/docs/behavior/layers.md
Labels: behaviors, enhancement

#100 Add `&none` behavior.
  app/CMakeLists.txt
  app/dts/behaviors.dtsi
  app/dts/behaviors/none.dtsi
  app/dts/bindings/behaviors/zmk,behavior-none.yaml
  app/src/behaviors/behavior_none.c
  docs/docs/behavior/misc.md
  docs/sidebars.js
Labels: behaviors, enhancement

#102 fix(bluetooth): Stop peripheral half advertising once connected.
  app/src/ble.c
Labels: bluetooth, bug

#99 Add magic combo for unpairing BT devices on start.
  app/CMakeLists.txt
  app/Kconfig
  app/boards/shields/corne/corne.dtsi
  app/boards/shields/corne/corne_left.conf
  app/boards/shields/corne/corne_left.overlay
  app/boards/shields/corne/corne_right.conf
  app/boards/shields/corne/corne_right.overlay
  app/boards/shields/kyria/kyria.dtsi
  app/boards/shields/kyria/kyria_left.conf
  app/boards/shields/kyria/kyria_left.overlay
  app/boards/shields/kyria/kyria_right.conf
  app/boards/shields/kyria/kyria_right.overlay
  app/boards/shields/lily58/lily58.dtsi
  app/boards/shields/lily58/lily58_left.conf
  app/boards/shields/lily58/lily58_left.overlay
  app/boards/shields/lily58/lily58_right.conf
  app/boards/shields/lily58/lily58_right.overlay
  app/drivers/zephyr/kscan_gpio_matrix.c
  app/dts/bindings/zmk,bt-unpair-combo.yaml
  app/include/zmk/ble.h
  app/src/ble.c
  app/src/ble_unpair_combo.c
Labels: bluetooth, core, enhancement

#106 refactor(boards): Rename to bluemicro840_v1.
  .github/workflows/build.yml
  app/boards/arm/bluemicro840/CMakeLists.txt
  app/boards/arm/bluemicro840/Kconfig
  app/boards/arm/bluemicro840/Kconfig.board
  app/boards/arm/bluemicro840/Kconfig.defconfig
  app/boards/arm/bluemicro840/arduino_pro_micro_pins.dtsi
  app/boards/arm/bluemicro840/bluemicro840_v1.dts
  app/boards/arm/bluemicro840/bluemicro840_v1.yaml
  app/boards/arm/bluemicro840/bluemicro840_v1_defconfig
  app/boards/arm/bluemicro840/board.cmake
  docs/docs/hardware.md
  docs/static/setup.sh
Labels: board, bug

#108 Build unpair combo behavior in if DT node is present.
  app/CMakeLists.txt
  app/Kconfig
  app/boards/shields/corne/corne_left.conf
  app/boards/shields/corne/corne_right.conf
  app/boards/shields/kyria/kyria_left.conf
  app/boards/shields/kyria/kyria_right.conf
  app/boards/shields/lily58/lily58_left.conf
  app/boards/shields/lily58/lily58_right.conf
  app/src/ble_unpair_combo.c
Labels: bluetooth, enhancement

#111 fix(shields): Load Kconfig for out-of-tree shields
  app/Kconfig
  app/cmake/zmk_config.cmake
Labels: board, bug

#130 [Keyboard] Add QAZ Shield
  app/boards/shields/qaz/Kconfig.defconfig
  app/boards/shields/qaz/Kconfig.shield
  app/boards/shields/qaz/qaz.keymap
  app/boards/shields/qaz/qaz.overlay
Labels: enhancement, shields

#136 feat(test): Add GH Action for tests.
  .github/workflows/test.yml
Labels: core, enhancement, tests

#135 Documentation update
  docs/docs/assets/bond-clearing/debug.log
  docs/docs/assets/bond-clearing/lily58.jpg
  docs/docs/assets/env-var/env_var.png
  docs/docs/assets/env-var/gnuarmemb.png
  docs/docs/assets/env-var/new_variable.png
  docs/docs/assets/env-var/start_menu.png
  docs/docs/assets/env-var/zephyr_toolchain.png
  docs/docs/assets/usb-logging/com.jpg
  docs/docs/assets/usb-logging/putty.jpg
  docs/docs/bond-reset.md
  docs/docs/customization.md
  docs/docs/dev-build.md
  docs/docs/dev-guide-usb-logging.md
  docs/docs/dev-setup.md
  docs/docs/feature/keymaps.md
  docs/docs/hardware.md
  docs/docs/intro.md
  docs/docs/user-setup.md
  docs/sidebars.js
Labels: documentation, enhancement
