Repository zmkfirmware/zmk, pull requests merged in 2020-11, with the labels that each got.

#322 fix(boards): Remap flash to account for bootloader
  app/boards/arm/bluemicro840/bluemicro840_v1.dts
  app/boards/arm/nice_nano/nice_nano.dts
  app/boards/arm/nrf52840_m2/nrf52840_m2.dts
  app/boards/arm/nrfmicro/nrfmicro_11.dts
  app/boards/arm/nrfmicro/nrfmicro_11_flipped.dts
  app/boards/arm/nrfmicro/nrfmicro_13.dts
Labels: board, core, enhancement

#324 docs: formatted with prettier
  docs/docs/dev-guide-new-shield.md
  docs/docs/dev-guide-usb-logging.md
  docs/docs/user-setup.md
Labels: documentation, refactor

#325 feat(docs): Add eslint and prettier GH Actions.
  .github/workflows/doc-checks.yml
  docs/package.json
Labels: documentation, enhancement

#326 feat(ci): Only build firmware when app/ changes.
  .github/workflows/build.yml
Labels: chore, core

#323 feat(underglow): Debounce state settings save to reduce flash wear
  app/src/rgb_underglow.c
Labels: core, enhancement, lighting

#270 Refactor Kconfig
  app/Kconfig
Labels: core, enhancement, hacktoberfest-accepted

#332 fix(keys): Replace GUI with Application / Context Menu
  app/include/dt-bindings/zmk/keys.h
Labels: bug, core, hid, keymaps

#334 docs(key press): Replace deprecated `NUM_1` with `N1`
  docs/docs/behavior/key-press.md
Labels: behaviors, bug, documentation, keymaps

#336 refactor(hid): Replace `0x01` with `HID_USAGE_CONSUMER_CONSUMER_CONTROL`
  app/include/zmk/hid.h
Labels: hid, refactor

#341 docs(codes): add modifier functions
  docs/docs/codes/_keyboard-keypad.mdx
  docs/docs/codes/modifiers.mdx
  docs/docs/dev-guide-new-shield.md
  docs/docs/feature/keymaps.md
  docs/sidebars.js
  docs/src/data/hid.js
Labels: documentation

#353 State Of The Firmware #3
  docs/blog/2020-08-12-zmk-sotf-1.md
  docs/blog/2020-09-21-zmk-sotf-2.md
  docs/blog/2020-11-09-zmk-sotf-3.md
Labels: documentation, enhancement

#351 refactor(app): Remove obsolete include's of `hid_usage_pages.h`
  app/dts/behaviors/key_press.dtsi
  app/dts/behaviors/sensor_rotate_key_press.dtsi
  app/src/hid.c
Labels: core, refactor

#345 fix(underglow): Add CONFIG_ to underglow Kconfigs
  app/boards/shields/corne/corne.conf
  app/boards/shields/microdox/microdox.conf
  docs/docs/feature/underglow.md
Labels: bug, documentation, lighting, shields

#357 fix(ble): Remove unpair combo code.
  app/CMakeLists.txt
  app/boards/shields/corne/corne.dtsi
  app/boards/shields/corne/corne_left.overlay
  app/boards/shields/corne/corne_right.overlay
  app/boards/shields/iris/iris.dtsi
  app/boards/shields/iris/iris_left.overlay
  app/boards/shields/iris/iris_right.overlay
  app/boards/shields/kyria/kyria.dtsi
  app/boards/shields/kyria/kyria_left.overlay
  app/boards/shields/kyria/kyria_right.overlay
  app/boards/shields/lily58/lily58.dtsi
  app/boards/shields/lily58/lily58_left.overlay
  app/boards/shields/lily58/lily58_right.overlay
  app/boards/shields/m60/m60.overlay
  app/boards/shields/romac/romac.overlay
  app/boards/shields/sofle/sofle.dtsi
  app/boards/shields/sofle/sofle_left.overlay
  app/boards/shields/sofle/sofle_right.overlay
  app/dts/bindings/zmk,bt-unpair-combo.yaml
  app/src/ble_unpair_combo.c
  docs/docs/assets/bond-clearing/corne.jpg
  docs/docs/assets/bond-clearing/debug.log
  docs/docs/assets/bond-clearing/kyria.jpg
  docs/docs/assets/bond-clearing/lily58.jpg
  docs/docs/bond-reset.md
  docs/docs/user-setup.md
Labels: bluetooth, core

#352 refactor(app): Replace `HID_EXT_USAGE` with `HID_USAGE`
  app/include/dt-bindings/zmk/hid_usage_pages.h
  app/include/dt-bindings/zmk/keys.h
  app/include/zmk/events/keycode-state-changed.h
Labels: core, hid, refactor

#360 fix(underglow): Switch from legacy SPI to SPIM
  app/boards/shields/corne/boards/nice_nano.overlay
  app/boards/shields/kyria/boards/nice_nano.overlay
  app/boards/shields/kyria/boards/nrfmicro_11.overlay
  app/boards/shields/kyria/boards/nrfmicro_11_flipped.overlay
  app/boards/shields/kyria/boards/nrfmicro_13.overlay
  app/boards/shields/microdox/boards/nice_nano.overlay
  app/boards/shields/reviung41/boards/nice_nano.overlay
  app/boards/shields/romac_plus/boards/nice_nano.overlay
  docs/docs/feature/underglow.md
Labels: help wanted, lighting

#349 boards: Cleanup and standardize features
  app/boards/arm/bluemicro840/bluemicro840_v1.dts
  app/boards/arm/nice_nano/nice_nano.dts
  app/boards/arm/nrf52840_m2/nrf52840_m2.dts
  app/boards/arm/nrfmicro/nrfmicro_11.dts
  app/boards/arm/nrfmicro/nrfmicro_11_flipped.dts
  app/boards/arm/nrfmicro/nrfmicro_13.dts
Labels: board, core, enhancement

#318 Fix connection to incorrect peripheral
  app/src/split/bluetooth/central.c
Labels: bluetooth, core, split

#342 docs: update modifier docs
  docs/docs/codes/modifiers.mdx
Labels: documentation

#364 refactor(docs): Remove explicit document ids
  docs/docs/customization.md
  docs/docs/dev-boards-shields-keymaps.md
  docs/docs/dev-build-flash.md
  docs/docs/dev-clean-room.md
  docs/docs/dev-guide-usb-logging.md
  docs/docs/dev-posix-board.md
  docs/docs/dev-setup.md
  docs/docs/dev-tests.md
  docs/docs/faq.md
  docs/docs/feature/keymaps.md
  docs/docs/hardware.md
  docs/docs/intro.md
  docs/docs/troubleshooting.md
  docs/docs/user-setup.md
Labels: documentation, refactor

#369 refactor(docs): Remove explicit document ids (part 2)
  docs/docs/dev-guide-new-shield.md
Labels: documentation, refactor

#391 QAZ shield keymap formatting tweaks.
  app/boards/shields/qaz/qaz.keymap
Labels: keymaps, refactor, shields

#388 add license headers to behavior dtsi files
  app/dts/behaviors/bluetooth.dtsi
  app/dts/behaviors/ext_power.dtsi
  app/dts/behaviors/key_press.dtsi
  app/dts/behaviors/layer_tap.dtsi
  app/dts/behaviors/mod_tap.dtsi
  app/dts/behaviors/momentary_layer.dtsi
  app/dts/behaviors/none.dtsi
  app/dts/behaviors/outputs.dtsi
  app/dts/behaviors/reset.dtsi
  app/dts/behaviors/rgb_underglow.dtsi
  app/dts/behaviors/sensor_rotate_key_press.dtsi
  app/dts/behaviors/transparent.dtsi
Labels: chore

#368 docs(key-press): Change `codes` to `usages`
  docs/docs/behaviors/key-press.md
Labels: documentation

#383 fix(docs): Remove obsolete VID/PID CMake error
  docs/docs/troubleshooting.md
Labels: documentation

#358 refactor(docs): Extract keymap examples into their own files
  docs/docs/dev-guide-new-shield.md
  docs/docs/features/keymaps.md
  docs/docs/keymap-example-file.md
  docs/docs/keymap-example.md
Labels: documentation, refactor

#371 docs: Rename `someSidebar` to `docs`
  docs/sidebars.js
Labels: documentation

#370 docs(hold-tap): Capitalize hold-tap behavior document title
  docs/docs/behaviors/hold-tap.md
Labels: behaviors, documentation

#407 fix(drivers): rename module.yaml to module.yml
  app/drivers/zephyr/module.yml
Labels: bug, core

#404 build: set zmk_config.cmake cmake_minimum_required to VERSION 3.15
  app/cmake/zmk_config.cmake
Labels: bug, core

#380 refactor(hid): Replace modifier usage values with their preprocessor definitions
  app/include/zmk/hid.h
Labels: core, hid, refactor

#367 improve hold-tap docs with better homerow example and more about flavors
  docs/docs/behaviors/hold-tap.md
Labels: behaviors, documentation

#413 docs(key-press): remove references to `key press`
  docs/docs/behaviors/key-press.md
Labels: documentation

#381 refactor: change `keypad` to `keyboard`
  app/include/zmk/hid.h
  app/include/zmk/hog.h
  app/src/endpoints.c
  app/src/hid.c
  app/src/hid_listener.c
  app/src/hog.c
Labels: core, hid, refactor

#414 refactor(hid): replace `kp_report` with `keyboard_report`
  app/src/hid.c
Labels: hid, refactor

#419 fix(ug): Start tick without settings state available
  app/src/rgb_underglow.c
Labels: bug, core, lighting

#434 refactor(workflows): remove `2-` prefix from cache keys
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: refactor

#348 feat: Add external power settings
  app/src/ext_power_generic.c
  app/src/main.c
Labels: core, enhancement

#441 build(west): add clone-depth = 1 to zephyr and uf2
  app/west.yml
Labels: core, enhancement

#440 chore(build): format west.yml
  app/west.yml
Labels: chore

#443 build(workflows): add each workflow to its own trigger conditions
  .github/workflows/build.yml
  .github/workflows/clang-format-lint.yml
  .github/workflows/doc-checks.yml
  .github/workflows/test.yml
Labels: core, enhancement

#433 refactor(workflows): align GitHub workflow conventions
  .github/workflows/build.yml
  .github/workflows/clang-format-lint.yml
  .github/workflows/doc-checks.yml
  .github/workflows/test.yml
Labels: refactor

#384 Updated function calls with missing reference. GPIO missing.
  app/drivers/zephyr/battery_voltage_divider.c
Labels: bug, core
