Repository zmkfirmware/zmk, pull requests merged in 2020-12, with the labels that each got.

#442 refactor(workflows): add `3-` prefix to cache keys
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: core, refactor

#397 refactor(ble): silence warning `auth_passkey_display` not used
  app/src/ble.c
Labels: core, refactor

#462 refactor(settings): Add Kconfig option for settings debounce
  app/Kconfig
  app/src/ext_power_generic.c
  app/src/rgb_underglow.c
Labels: core, enhancement

#400 refactor: align drivers with Zephyr file system conventions
  app/drivers/CMakeLists.txt
  app/drivers/Kconfig
  app/drivers/kscan/CMakeLists.txt
  app/drivers/kscan/Kconfig
  app/drivers/kscan/kscan_gpio_demux.c
  app/drivers/kscan/kscan_gpio_direct.c
  app/drivers/kscan/kscan_gpio_matrix.c
  app/drivers/sensor/CMakeLists.txt
  app/drivers/sensor/Kconfig
  app/drivers/sensor/battery_voltage_divider/CMakeLists.txt
  app/drivers/sensor/battery_voltage_divider/Kconfig
  app/drivers/sensor/battery_voltage_divider/battery_voltage_divider.c
  app/drivers/sensor/ec11/CMakeLists.txt
  app/drivers/sensor/ec11/Kconfig
  app/drivers/sensor/ec11/ec11.c
  app/drivers/sensor/ec11/ec11.h
  app/drivers/sensor/ec11/ec11_trigger.c
  app/drivers/zephyr/CMakeLists.txt
  app/drivers/zephyr/dts/bindings/kscan/zmk,kscan-gpio-demux.yaml
  app/drivers/zephyr/dts/bindings/kscan/zmk,kscan-gpio-direct.yaml
  app/drivers/zephyr/dts/bindings/kscan/zmk,kscan-gpio-matrix.yaml
  app/drivers/zephyr/dts/bindings/sensor/alps,ec11.yaml
  app/drivers/zephyr/dts/bindings/sensor/zmk,battery-voltage-divider.yaml
  app/drivers/zephyr/module.yml
Labels: core, refactor

#458 ci(build): sort boards and shields alphabetically
  .github/workflows/build.yml
Labels: refactor

#463 ci(build): remove proton_c guard from uf2 archive step
  .github/workflows/build.yml
Labels: refactor

#406 build: Remove unnecessary SYSCALL_INCLUDE_DIRS for drivers
  app/CMakeLists.txt
Labels: core, refactor

#468 build(west): migrate to zmkfirmware/zephyr fork
  app/west.yml
Labels: refactor

#474 refactor(devcontainer): format with prettier
  .devcontainer/devcontainer.json
Labels: refactor

#449 Bugfix: sticky key multiple presses
  app/src/behaviors/behavior_sticky_key.c
  app/tests/sticky-keys/9-sk-dn-up-dn-up/events.patterns
  app/tests/sticky-keys/9-sk-dn-up-dn-up/keycode_events.snapshot
  app/tests/sticky-keys/9-sk-dn-up-dn-up/native_posix.keymap
Labels: behaviors, bug, refactor

#476 refactor(devcontainer): reorder properties
  .devcontainer/devcontainer.json
Labels: refactor

#483 add CRBN shield
  .github/workflows/build.yml
  app/boards/shields/crbn/Kconfig.defconfig
  app/boards/shields/crbn/Kconfig.shield
  app/boards/shields/crbn/crbn.conf
  app/boards/shields/crbn/crbn.keymap
  app/boards/shields/crbn/crbn.overlay
  app/boards/shields/crbn/readme.md
  docs/docs/hardware.md
  docs/static/setup.ps1
  docs/static/setup.sh
Labels: enhancement, shields

#488 Add note about cmake 3.19 not working with zephr ; addresses issue #487
  docs/docs/development/setup.md
Labels: documentation, enhancement

#477 feat(devcontainer): add forwardPorts 3000
  .devcontainer/devcontainer.json
Labels: enhancement

#478 ci(build): add missing boards
  .github/workflows/build.yml
Labels: refactor

#485 ci(build): add zmk.hex to archive
  .github/workflows/build.yml
Labels: enhancement

#482 update doc about bluetooth
  docs/docs/behaviors/bluetooth.md
  docs/docs/user-setup.md
Labels: documentation, enhancement

#492 fix(kscan): Fix building kscan for tests.
  app/CMakeLists.txt
  app/drivers/kscan/CMakeLists.txt
  app/drivers/kscan/Kconfig
  app/drivers/kscan/kscan_composite.c
  app/drivers/kscan/kscan_mock.c
Labels: bug, core

#377 docs: add macos undocumented keycodes
  docs/docs/codes/_footnotes/macos-power.mdx
  docs/src/data/footnotes.js
  docs/src/data/hid.js
Labels: documentation, enhancement

#484 Add layer change event
  app/CMakeLists.txt
  app/include/zmk/events/layer-state-changed.h
  app/include/zmk/keymap.h
  app/src/events/layer_state_changed.c
  app/src/keymap.c
Labels: core, enhancement

#401 improvement: upgrade default keymaps
  app/boards/arm/dz60rgb/dz60rgb_rev1.keymap
  app/boards/arm/planck/planck_rev6.keymap
  app/boards/shields/boardsource3x4/boardsource3x4.keymap
  app/boards/shields/clueboard_california/clueboard_california.keymap
  app/boards/shields/corne/corne.keymap
  app/boards/shields/cradio/cradio.keymap
  app/boards/shields/iris/iris.keymap
  app/boards/shields/jian/jian.keymap
  app/boards/shields/jorne/jorne.keymap
  app/boards/shields/kyria/kyria.keymap
  app/boards/shields/lily58/lily58.keymap
  app/boards/shields/m60/m60.keymap
  app/boards/shields/microdox/microdox.keymap
  app/boards/shields/nibble/nibble.keymap
  app/boards/shields/qaz/qaz.keymap
  app/boards/shields/quefrency/quefrency.keymap
  app/boards/shields/reviung41/reviung41.keymap
  app/boards/shields/romac/romac.keymap
  app/boards/shields/romac_plus/romac_plus.keymap
  app/boards/shields/sofle/sofle.keymap
  app/boards/shields/splitreus62/splitreus62.keymap
  app/boards/shields/tg4x/tg4x.keymap
Labels: enhancement, keymaps

#344 feat(docs): add keymap upgrader
  docs/docs/codes/keymap-upgrader.mdx
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
  docs/sidebars.js
  docs/src/components/KeymapUpgrader/index.jsx
  docs/src/components/KeymapUpgrader/styles.module.css
  docs/src/data/keymap-upgrade.js
  docs/src/docusaurus-tree-sitter-plugin/index.js
  docs/src/keymap-upgrade.js
  docs/static/tree-sitter-devicetree.wasm
  docs/static/tree-sitter.wasm
Labels: documentation, enhancement, keymaps, user configs

#494 fix(west) test command should not swallow errors.
  app/scripts/west_commands/test.py
Labels: bug, core, tests

#496 ci(build): remove artifact uf2 suffix
  .github/workflows/build.yml
Labels: enhancement

#479 feat(devcontainer): add volume mount for root user
  .devcontainer/devcontainer.json
Labels: enhancement

#498 ci(workflows): remove zephyr.base-prefer configfile
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: refactor

#501 ci(docs-checks): remove prettier name
  .github/workflows/doc-checks.yml
Labels: refactor

#503 ci: remove unnecessary comments
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: refactor

#450 sticky keys refactor
  app/src/behaviors/behavior_sticky_key.c
Labels: behaviors, refactor

#424 Initial nullbitsco tidbit bring up
  .github/workflows/build.yml
  app/boards/shields/tidbit/Kconfig.defconfig
  app/boards/shields/tidbit/Kconfig.shield
  app/boards/shields/tidbit/README.md
  app/boards/shields/tidbit/boards/nice_nano.conf
  app/boards/shields/tidbit/boards/nice_nano.overlay
  app/boards/shields/tidbit/boards/proton_c.conf
  app/boards/shields/tidbit/tidbit.conf
  app/boards/shields/tidbit/tidbit.dtsi
  app/boards/shields/tidbit/tidbit.keymap
  app/boards/shields/tidbit/tidbit.overlay
  app/boards/shields/tidbit/tidbit_19key.conf
  app/boards/shields/tidbit/tidbit_19key.keymap
  app/boards/shields/tidbit/tidbit_19key.overlay
  docs/docs/hardware.md
  docs/static/setup.ps1
  docs/static/setup.sh
Labels: enhancement, shields

#356 docs: update untested iOS keyboard codes
  docs/docs/codes/_footnotes/ios-application.mdx
  docs/docs/codes/_footnotes/ios-power.mdx
  docs/src/data/footnotes.js
  docs/src/data/hid.js
Labels: documentation, enhancement

#522 refactor(endpoints): rename usage_report parameter to usage_page
  app/include/zmk/endpoints.h
Labels: core, refactor

#515 ci: improve step names
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: enhancement

#480 feat(devcontainer): persist bash history
  .devcontainer/devcontainer.json
Labels: enhancement

#520 fix(sticky keys): add 0xFF mask to usage_page
  app/src/behaviors/behavior_sticky_key.c
Labels: behaviors, bug

#519 feat(devcontainer): add volume mounts for zephyr, modules and tools
  .devcontainer/devcontainer.json
Labels: enhancement

#517 docs(setup): bump Zephyr SDK version to 0.11.4
  docs/docs/development/setup.md
Labels: documentation

#538 ci(build): ignore failing upload-artifacts step
  .github/workflows/build.yml
Labels: bug

#535 chore(display): align status_screen copyright
  app/include/zmk/display/status_screen.h
  app/src/display/status_screen.c
Labels: chore, displays

#526 refactor(app): remove handlers.h
  app/include/zmk/handlers.h
Labels: core, refactor

#534 chore(display): add header to Kconfig
  app/src/display/Kconfig
  app/src/display/widgets/Kconfig
Labels: chore, displays

#530 refactor(app): remove zmk_action
  app/include/zmk/keys.h
Labels: core, refactor

#533 chore(display): add header to CMakeLists.txt
  app/src/display/CMakeLists.txt
  app/src/display/widgets/CMakeLists.txt
Labels: chore, displays

#500 feature(ci): Build split w/ display enabled for testing.
  .github/workflows/build.yml
Labels: displays

#493 Add uppermost, current layer status widget to oled
  app/include/zmk/display/widgets/layer_status.h
  app/src/display/CMakeLists.txt
  app/src/display/status_screen.c
  app/src/display/widgets/CMakeLists.txt
  app/src/display/widgets/Kconfig
  app/src/display/widgets/layer_status.c
Labels: enhancement, lighting

#417 feat(ext-power): Cut power when PM is sleeping
  app/Kconfig
  app/src/ext_power_generic.c
  app/src/power.c
Labels: core, enhancement

#489 (feature) Add &to keycode/behavior
  app/CMakeLists.txt
  app/dts/behaviors.dtsi
  app/dts/behaviors/to_layer.dtsi
  app/dts/bindings/behaviors/zmk,behavior-to-layer.yaml
  app/include/zmk/keymap.h
  app/src/behaviors/behavior_to_layer.c
  app/src/keymap.c
  app/tests/to-layer/behavior_keymap.dtsi
  app/tests/to-layer/normal/events.patterns
  app/tests/to-layer/normal/keycode_events.snapshot
  app/tests/to-layer/normal/native_posix.keymap
  docs/docs/behaviors/layers.md
Labels: behaviors, enhancement
