Repository zmkfirmware/zmk, pull requests merged in 2020-10, with the labels that each got.

#229 chore: Fix remaining formatting issues.
  app/drivers/zephyr/kscan_gpio_direct.c
Labels: bug, chore, core

#230 Update nano link to actual product page
  docs/docs/hardware.md
Labels: documentation

#231 Add API to access current USB status
  app/include/zmk/usb_hid.h
  app/src/usb_hid.c
Labels: core, enhancement, usb

#227 Add missing licensing header
  app/include/dt-bindings/zmk/keys.h
  app/include/dt-bindings/zmk/kscan-mock.h
  app/include/dt-bindings/zmk/matrix-transform.h
  app/include/dt-bindings/zmk/rgb.h
  app/include/zmk/split/bluetooth/service.h
  app/include/zmk/split/bluetooth/uuid.h
Labels: chore

#238 Expose USB status without having USB HID output.
  app/CMakeLists.txt
  app/Kconfig
  app/include/zmk/usb.h
  app/src/endpoints.c
  app/src/usb.c
Labels: core, refactor, usb

#233 Shield and board definitions for M60
  app/boards/arm/nrf52840_m2/CMakeLists.txt
  app/boards/arm/nrf52840_m2/Kconfig
  app/boards/arm/nrf52840_m2/Kconfig.board
  app/boards/arm/nrf52840_m2/Kconfig.defconfig
  app/boards/arm/nrf52840_m2/board.cmake
  app/boards/arm/nrf52840_m2/nrf52840_m2.dts
  app/boards/arm/nrf52840_m2/nrf52840_m2.yaml
  app/boards/arm/nrf52840_m2/nrf52840_m2_defconfig
  app/boards/shields/clueboard_california/clueboard_california.keymap
  app/boards/shields/corne/corne.keymap
  app/boards/shields/iris/iris.keymap
  app/boards/shields/kyria/kyria.keymap
  app/boards/shields/lily58/lily58.keymap
  app/boards/shields/m60/Kconfig.defconfig
  app/boards/shields/m60/Kconfig.shield
  app/boards/shields/m60/m60.conf
  app/boards/shields/m60/m60.keymap
  app/boards/shields/m60/m60.overlay
  app/boards/shields/m60/readme.md
  app/boards/shields/romac/romac.keymap
  app/boards/shields/sofle/sofle.keymap
  app/boards/shields/splitreus62/splitreus62.keymap
Labels: board, shields

#211 Use PORT events for kscan matrix interrupts, add option for deep sleep.
  app/CMakeLists.txt
  app/Kconfig
  app/boards/arm/nice_nano/nice_nano.dts
  app/drivers/zephyr/kscan_gpio_matrix.c
  app/include/dt-bindings/zmk/bt.h
  app/src/power.c
Labels: core, enhancement, help wanted

#243 Correct typo in previous profile behaviour binding in bluetooth.md
  docs/docs/behavior/bluetooth.md
Labels: bug, documentation

#252 Upload all UF2 images on GH action build
  .github/workflows/build.yml
Labels: core, enhancement

#245 Add Microdox Shield
  app/boards/shields/microdox/Kconfig.defconfig
  app/boards/shields/microdox/Kconfig.shield
  app/boards/shields/microdox/boards/nice_nano.overlay
  app/boards/shields/microdox/microdox.conf
  app/boards/shields/microdox/microdox.dtsi
  app/boards/shields/microdox/microdox.keymap
  app/boards/shields/microdox/microdox_left.conf
  app/boards/shields/microdox/microdox_left.overlay
  app/boards/shields/microdox/microdox_right.conf
  app/boards/shields/microdox/microdox_right.overlay
Labels: enhancement, shields

#254 Documented Issue #220
  docs/docs/bond-reset.md
  docs/docs/troubleshooting.md
  docs/sidebars.js
Labels: bluetooth, documentation, enhancement

#242 [RDY] Driver to control the external power output
  app/CMakeLists.txt
  app/Kconfig
  app/boards/arm/nice_nano/nice_nano.dts
  app/boards/arm/nrfmicro/nrfmicro_11.dts
  app/boards/arm/nrfmicro/nrfmicro_11_flipped.dts
  app/boards/arm/nrfmicro/nrfmicro_13.dts
  app/boards/arm/nrfmicro/pinmux.c
  app/dts/bindings/behaviors/zmk,behavior-sensor-rotate-key-press.yaml
  app/dts/bindings/zmk,ext-power-generic.yaml
  app/dts/bindings/zmk,keymap-sensors.yaml
  app/include/drivers/ext_power.h
  app/src/ext_power_generic.c
  app/src/main.c
Labels: core, enhancement

#209 Add VSCode devcontainer configuration
  .devcontainer/.bashrc
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  docs/docs/assets/dev-setup/vscode_devcontainer.png
  docs/docs/dev-setup.md
Labels: core, documentation, enhancement

#255 -DZMK_CONFIG Documentation
  docs/docs/dev-build.md
Labels: documentation, enhancement, user configs

#256 Exit setup if no write permissions in directory
  docs/static/setup.ps1
  docs/static/setup.sh
Labels: enhancement, user configs

#268 fix: don't leak bt_conn refs
  app/src/hog.c
Labels: bluetooth

#260 Issue #210 Document Setup.ps
  docs/docs/user-setup.md
Labels: documentation, enhancement, user configs

#259 Issue: #197 Added Setup Instructions for `dfu-util`
  docs/docs/dev-setup.md
Labels: documentation

#226 Add TG4X rev 2.1 shield
  app/boards/shields/tg4x/Kconfig.defconfig
  app/boards/shields/tg4x/Kconfig.shield
  app/boards/shields/tg4x/tg4x.keymap
  app/boards/shields/tg4x/tg4x.overlay
Labels: enhancement, shields

#258 New behavior for ext power control
  app/CMakeLists.txt
  app/boards/shields/lily58/lily58.keymap
  app/dts/behaviors.dtsi
  app/dts/behaviors/ext_power.dtsi
  app/dts/bindings/behaviors/zmk,behavior-ext-power.yaml
  app/include/dt-bindings/zmk/ext_power.h
  app/src/behaviors/behavior_ext_power.c
  app/src/behaviors/behavior_key_press.c
Labels: behaviors, enhancement

#257 Adressing Issue #181 - Split Keyboard Documentation
  docs/docs/dev-guide-new-shield.md
Labels: documentation

#265 Addressing #138 - ZMK Config Folders
  docs/docs/customization.md
Labels: documentation, enhancement, user configs

#250 Added Feature Matrix for Intro.md
  docs/docs/intro.md
Labels: documentation, enhancement

#224 Cradio
  app/boards/shields/Kconfig.defconfig
  app/boards/shields/Kconfig.shield
  app/boards/shields/cradio/Kconfig.defconfig
  app/boards/shields/cradio/Kconfig.shield
  app/boards/shields/cradio/cradio.dtsi
  app/boards/shields/cradio/cradio.keymap
  app/boards/shields/cradio/cradio_left.conf
  app/boards/shields/cradio/cradio_left.overlay
  app/boards/shields/cradio/cradio_right.conf
  app/boards/shields/cradio/cradio_right.overlay
Labels: enhancement, shields

#282 BLE: Only advertise when needed.
  app/src/ble.c
Labels: bluetooth, enhancement

#285 Use official USB product ID
  app/Kconfig
Labels: core, enhancement

#109 Add RGB underglow state Kconfig and settings
  app/CMakeLists.txt
  app/Kconfig
  app/src/rgb_underglow.c
  app/src/settings.c
  docs/docs/feature/underglow.md
Labels: core, enhancement

#290 chore(docs): Docusaurus 2.0.0 alpha.65
  docs/blog/2020-05-24-wip.md
  docs/docs/dev-guide-new-shield.md
  docs/docs/intro.md
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
Labels: chore, documentation, enhancement

#291 chore(docs): Docusaurus 2.0.0-alpha.66
  docs/package-lock.json
  docs/package.json
Labels: chore, documentation, enhancement

#280 DocumentedTX Power Config in Troubleshooting
  docs/docs/troubleshooting.md
Labels: documentation, enhancement, shields

#264 Add support for wget to setup.sh
  docs/docs/user-setup.md
  docs/static/setup.sh
Labels: enhancement, user configs

#302 docs: Add missing docusaurus scripts
  docs/package.json
Labels: chore, documentation

#293 Add Battery Voltage Divider Driver
  app/boards/arm/bluemicro840/Kconfig.defconfig
  app/boards/arm/bluemicro840/bluemicro840_v1.dts
  app/boards/arm/nice_nano/Kconfig.defconfig
  app/boards/arm/nice_nano/nice_nano.dts
  app/boards/arm/nrfmicro/Kconfig.defconfig
  app/boards/arm/nrfmicro/nrfmicro_13.dts
  app/drivers/zephyr/CMakeLists.txt
  app/drivers/zephyr/Kconfig
  app/drivers/zephyr/battery_voltage_divider.c
  app/drivers/zephyr/dts/bindings/zmk,battery-voltage-divider.yaml
Labels: core, enhancement

#263 fix: allow nested zmk-config for dev container
  .gitignore
Labels: core, enhancement, user configs

#303 feat(kscan_mock): Increase max number of events
  app/src/kscan_mock.c
Labels: core, enhancement, tests

#297 Add Reviung41 Shield Definitions
  .github/workflows/build.yml
  app/boards/shields/reviung41/Kconfig.defconfig
  app/boards/shields/reviung41/Kconfig.shield
  app/boards/shields/reviung41/boards/nice_nano.overlay
  app/boards/shields/reviung41/reviung41.conf
  app/boards/shields/reviung41/reviung41.keymap
  app/boards/shields/reviung41/reviung41.overlay
  docs/docs/hardware.md
  docs/static/setup.ps1
  docs/static/setup.sh
Labels: keymaps, shields

#301 docs: Add eslint, prettier and eslint-mdx support
  docs/.eslintignore
  docs/.eslintrc.js
  docs/.prettierignore
  docs/.prettierrc.js
  docs/README.md
  docs/docs/behavior/hold-tap.md
  docs/docs/behavior/key-press.md
  docs/docs/behavior/layers.md
  docs/docs/behavior/mod-tap.md
  docs/docs/behavior/power.md
  docs/docs/bond-reset.md
  docs/docs/customization.md
  docs/docs/dev-build.md
  docs/docs/dev-guide-new-shield.md
  docs/docs/dev-guide-usb-logging.md
  docs/docs/dev-setup.md
  docs/docs/dev-tests.md
  docs/docs/faq.md
  docs/docs/feature/underglow.md
  docs/docs/intro.md
  docs/docs/troubleshooting.md
  docs/docs/user-setup.md
  docs/package-lock.json
  docs/package.json
  docs/sidebars.js
  docs/src/pages/index.js
Labels: chore, documentation

#304 Explicitly license documentation as CC-BY-NC-SA.
  docs/README.md
  docs/docusaurus.config.js
Labels: documentation, enhancement

#292 Add zmk_kscan_gpio_demux kscan driver & NIBBLE keyboard
  .github/workflows/build.yml
  .vscode/settings.json
  app/boards/shields/nibble/Kconfig.defconfig
  app/boards/shields/nibble/Kconfig.shield
  app/boards/shields/nibble/nibble.conf
  app/boards/shields/nibble/nibble.keymap
  app/boards/shields/nibble/nibble.overlay
  app/drivers/zephyr/CMakeLists.txt
  app/drivers/zephyr/dts/bindings/zmk,kscan-gpio-demux.yaml
  app/drivers/zephyr/kscan_gpio_demux.c
  docs/static/setup.ps1
  docs/static/setup.sh
Labels: core, enhancement, shields

#296 Add Boardsource 3x4 shield
  .github/workflows/build.yml
  app/boards/shields/boardsource3x4/Kconfig.defconfig
  app/boards/shields/boardsource3x4/Kconfig.shield
  app/boards/shields/boardsource3x4/boardsource3x4.conf
  app/boards/shields/boardsource3x4/boardsource3x4.keymap
  app/boards/shields/boardsource3x4/boardsource3x4.overlay
Labels: enhancement, shields

#309 docs: Set netlify node version to lts/*
  docs/.nvmrc
Labels: bug, chore, documentation

#313 refactor(hid): configurable NKRO integer arrays & boot friendly
  app/include/zmk/hid.h
  app/src/hid.c
Labels: enhancement, hid, refactor

#269 feat: only send HID reports to one endpoint
  app/CMakeLists.txt
  app/dts/behaviors.dtsi
  app/dts/behaviors/outputs.dtsi
  app/dts/bindings/behaviors/zmk,behavior-outputs.yaml
  app/include/dt-bindings/zmk/outputs.h
  app/include/zmk/ble.h
  app/include/zmk/endpoints.h
  app/include/zmk/events/usb-conn-state-changed.h
  app/include/zmk/hid.h
  app/include/zmk/usb.h
  app/src/behaviors/behavior_outputs.c
  app/src/ble.c
  app/src/endpoints.c
  app/src/events/usb_conn_state_changed.c
  app/src/hid.c
  app/src/power.c
  app/src/usb.c
  docs/docs/behavior/outputs.md
  docs/sidebars.js
Labels: behaviors, bluetooth, core, enhancement, hacktoberfest-accepted, hid, usb

#317 docs(outputs): run prettier on outputs.md
  docs/docs/behavior/outputs.md
Labels: documentation
