Repository zmkfirmware/zmk, pull requests merged in 2020-09, with the labels that each got.

#163 Add RoMac / non-split template support
  docs/static/setup.sh
Labels: enhancement, shields, user configs

#133 feat(bluetooth): Proper basic bond management, new `bt` behavior for resetting bond to host.
  .github/workflows/build.yml
  app/CMakeLists.txt
  app/Kconfig
  app/boards/shields/settings_reset/Kconfig.defconfig
  app/boards/shields/settings_reset/Kconfig.shield
  app/boards/shields/settings_reset/settings_reset.conf
  app/boards/shields/settings_reset/settings_reset.keymap
  app/boards/shields/settings_reset/settings_reset.overlay
  app/dts/behaviors.dtsi
  app/dts/behaviors/bluetooth.dtsi
  app/dts/bindings/behaviors/zmk,behavior-bluetooth.yaml
  app/include/dt-bindings/zmk/bt.h
  app/include/zmk/ble.h
  app/include/zmk/ble/profile.h
  app/include/zmk/events/ble-active-profile-changed.h
  app/src/behaviors/behavior_bt.c
  app/src/ble.c
  app/src/events/ble_active_profile_changed.c
  app/src/hog.c
  app/src/split/bluetooth/central.c
  app/src/split/bluetooth/service.c
  app/src/split_listener.c
  docs/docs/behavior/bluetooth.md
  docs/sidebars.js
Labels: bluetooth, core, enhancement, split

#184 feature(board): add BT prof management to defaults
  app/boards/shields/corne/corne.keymap
  app/boards/shields/iris/iris.keymap
  app/boards/shields/lily58/lily58.keymap
  app/boards/shields/qaz/qaz.keymap
  app/boards/shields/romac/romac.keymap
  app/boards/shields/sofle/sofle.keymap
Labels: bluetooth, board

#183 Standardize code formatting using clang-format w/ LLVM style
  .clang-format
  .github/workflows/clang-format-lint.yml
  app/boards/arm/dz60rgb/pinmux.c
  app/boards/arm/nrfmicro/pinmux.c
  app/boards/arm/planck/pinmux.c
  app/boards/arm/proton_c/pinmux.c
  app/drivers/zephyr/ec11.c
  app/drivers/zephyr/ec11.h
  app/drivers/zephyr/ec11_trigger.c
  app/drivers/zephyr/kscan_gpio_direct.c
  app/drivers/zephyr/kscan_gpio_matrix.c
  app/include/drivers/behavior.h
  app/include/dt-bindings/zmk/bt.h
  app/include/dt-bindings/zmk/keys.h
  app/include/dt-bindings/zmk/reset.h
  app/include/zmk/event-manager.h
  app/include/zmk/events/ble-active-profile-changed.h
  app/include/zmk/events/keycode-state-changed.h
  app/include/zmk/events/modifiers-state-changed.h
  app/include/zmk/hid.h
  app/include/zmk/keys.h
  app/include/zmk/matrix.h
  app/include/zmk/split/bluetooth/uuid.h
  app/src/behaviors/behavior_bt.c
  app/src/behaviors/behavior_hold_tap.c
  app/src/behaviors/behavior_key_press.c
  app/src/behaviors/behavior_momentary_layer.c
  app/src/behaviors/behavior_none.c
  app/src/behaviors/behavior_reset.c
  app/src/behaviors/behavior_rgb_underglow.c
  app/src/behaviors/behavior_sensor_rotate_key_press.c
  app/src/behaviors/behavior_toggle_layer.c
  app/src/behaviors/behavior_transparent.c
  app/src/ble.c
  app/src/ble_unpair_combo.c
  app/src/display.c
  app/src/endpoints.c
  app/src/event_manager.c
  app/src/hid.c
  app/src/hid_listener.c
  app/src/hog.c
  app/src/keymap.c
  app/src/kscan.c
  app/src/kscan_composite.c
  app/src/kscan_mock.c
  app/src/main.c
  app/src/matrix_transform.c
  app/src/rgb_underglow.c
  app/src/sensors.c
  app/src/split/bluetooth/central.c
  app/src/split/bluetooth/service.c
  app/src/split_listener.c
  app/src/usb_hid.c
Labels: core, enhancement

#159 update intro page, add layer-tap docs and update hold-tap docs.
  docs/docs/behavior/hold-tap.md
  docs/docs/behavior/layers.md
  docs/docs/intro.md
Labels: behaviors, documentation, enhancement

#187 Fixed Iris default build/Updated Dev Guide
  .github/workflows/build.yml
  app/boards/shields/iris/iris.keymap
  docs/docs/dev-guide-new-shield.md
Labels: documentation, enhancement, shields, split

#194 Initial CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: documentation, enhancement

#196 Blog - State of the firmware #2
  docs/blog/2020-09-21-zmk-sotf-2.md
Labels: documentation, enhancement

#198 RoMac+ v4 Support for nice!nano v1
  .github/workflows/build.yml
  app/boards/shields/romac_plus/Kconfig.defconfig
  app/boards/shields/romac_plus/Kconfig.shield
  app/boards/shields/romac_plus/boards/nice_nano.overlay
  app/boards/shields/romac_plus/romac_plus.conf
  app/boards/shields/romac_plus/romac_plus.dtsi
  app/boards/shields/romac_plus/romac_plus.keymap
  app/boards/shields/romac_plus/romac_plus.overlay
Labels: enhancement, shields

#216 Add quefrency shield
  .github/workflows/build.yml
  app/boards/shields/quefrency/Kconfig.defconfig
  app/boards/shields/quefrency/Kconfig.shield
  app/boards/shields/quefrency/quefrency.conf
  app/boards/shields/quefrency/quefrency.dtsi
  app/boards/shields/quefrency/quefrency.keymap
  app/boards/shields/quefrency/quefrency_left.conf
  app/boards/shields/quefrency/quefrency_left.overlay
  app/boards/shields/quefrency/quefrency_right.conf
  app/boards/shields/quefrency/quefrency_right.overlay
Labels: enhancement, shields

#222 Fix max paired/connected settings for all configs.
  app/Kconfig
Labels: bluetooth, bug, core
