Repository zmkfirmware/zmk, pull requests merged in 2021-09, with the labels that each got.

#931 fix: Add missing semicolons for tidbit and eek in setup script
  docs/static/setup.sh
Labels: bug, user configs, shields

#933 fix(shield): Add note about Cradio pin arrangement
  app/boards/shields/cradio/README.md
Labels: documentation, shields

#937 fix(setup): Fix setup.ps1 to check Get-Acl exists
  docs/src/templates/setup.ps1.mustache
Labels: bug, documentation, user configs

#915 feat(docs): Add note to clarify shared .conf files do not apply outside zmk-config
  docs/docs/development/new-shield.md
Labels: documentation

#932 Fix macOS setpup docs
  docs/docs/development/setup.md
Labels: documentation

#914 feat(docs) Clarify Bluetooth profile pairing
  docs/docs/behaviors/bluetooth.md
Labels: documentation

#945 fix(docs): Set "Mouse Keys" as "Under Development"
  docs/docs/intro.md
Labels: documentation

#946 Add encrypted perm for HID report map/ref.
  app/src/hog.c
Labels: bug, core, bluetooth

#952 fix(docs): Remove build.yml from new shield steps
  docs/docs/development/new-shield.md
Labels: documentation

#957 fix(setup): Fix sed delimiters for Cradio
  docs/src/templates/setup.sh.mustache
Labels: bug, user configs

#872 refactor(display): Saner font selection/defaults.
  app/src/display/Kconfig
  app/src/display/status_screen.c
  app/src/display/widgets/Kconfig
  app/src/display/widgets/battery_status.c
  app/src/display/widgets/layer_status.c
  app/src/display/widgets/output_status.c
  app/src/display/widgets/wpm_status.c
Labels: displays, refactor
