Repository zmkfirmware/zmk, pull requests merged in 2021-01, with the labels that each got.

#541 docs(codes): macOS Support: Brightness and media keycode compatability for MacOS Catalina 10.15.7
  docs/src/data/hid.js
Labels: documentation, enhancement, help wanted

#529 Eek
  .github/workflows/build.yml
  app/boards/shields/eek/Kconfig.defconfig
  app/boards/shields/eek/Kconfig.shield
  app/boards/shields/eek/eek.conf
  app/boards/shields/eek/eek.keymap
  app/boards/shields/eek/eek.overlay
  app/boards/shields/eek/readme.md
  docs/docs/hardware.md
  docs/static/setup.ps1
  docs/static/setup.sh
Labels: enhancement, shields

#542 (feat/enhance) Add ws2812 to lilly58 + nice!nano
  app/boards/shields/lily58/boards/nice_nano.overlay
Labels: enhancement, lighting, shields

#563 refactor(app): format with prettier
  app/boards/shields/eek/readme.md
  app/drivers/zephyr/dts/bindings/sensor/zmk,battery-voltage-divider.yaml
  app/dts/bindings/behaviors/zmk,behavior-sticky-key.yaml
  app/dts/bindings/zmk,ext-power-generic.yaml
Labels: refactor

#565 chore: standardize C style headers
  app/boards/arm/nrf52840_m2/nrf52840_m2.dts
  app/boards/shields/jorne/jorne.dtsi
  app/boards/shields/jorne/jorne_left.overlay
  app/boards/shields/jorne/jorne_right.overlay
Labels: chore

#472 BFO-9000 Shield
  .github/workflows/build.yml
  app/boards/shields/bfo9000/Kconfig.defconfig
  app/boards/shields/bfo9000/Kconfig.shield
  app/boards/shields/bfo9000/bfo9000.conf
  app/boards/shields/bfo9000/bfo9000.dtsi
  app/boards/shields/bfo9000/bfo9000.keymap
  app/boards/shields/bfo9000/bfo9000_left.conf
  app/boards/shields/bfo9000/bfo9000_left.overlay
  app/boards/shields/bfo9000/bfo9000_right.conf
  app/boards/shields/bfo9000/bfo9000_right.overlay
  app/boards/shields/bfo9000/readme.md
  docs/docs/hardware.md
  docs/static/setup.ps1
  docs/static/setup.sh
Labels: enhancement, shields

#574 docs(shield): Remove SPLIT_BLE_ROLE_PERIPHERAL
  docs/docs/development/new-shield.md
Labels: documentation

#429 Initial bring-up of Helix keyboard shield
  .github/workflows/build.yml
  app/boards/shields/helix/Kconfig.defconfig
  app/boards/shields/helix/Kconfig.shield
  app/boards/shields/helix/README.md
  app/boards/shields/helix/boards/nice_nano.overlay
  app/boards/shields/helix/helix.conf
  app/boards/shields/helix/helix.dtsi
  app/boards/shields/helix/helix.keymap
  app/boards/shields/helix/helix_left.overlay
  app/boards/shields/helix/helix_right.overlay
  docs/docs/hardware.md
  docs/static/setup.ps1
  docs/static/setup.sh
Labels: enhancement, shields

#512 docs(troubleshooting): fix instructions on how to download the reset uf2
  docs/docs/troubleshooting.md
Labels: documentation

#558 docs(intro): Update feature table
  docs/docs/intro.md
Labels: documentation

#564 chore: standardize # style headers
  app/boards/arm/nrf52840_m2/CMakeLists.txt
  app/boards/arm/nrf52840_m2/Kconfig
  app/boards/arm/nrf52840_m2/Kconfig.board
  app/boards/arm/nrf52840_m2/Kconfig.defconfig
  app/boards/arm/nrf52840_m2/board.cmake
  app/boards/arm/nrf52840_m2/nrf52840_m2_defconfig
  app/boards/shields/crbn/Kconfig.defconfig
  app/boards/shields/crbn/Kconfig.shield
  app/boards/shields/eek/Kconfig.defconfig
  app/boards/shields/jorne/Kconfig.shield
  app/boards/shields/m60/Kconfig.defconfig
  app/boards/shields/m60/Kconfig.shield
  app/boards/shields/quefrency/Kconfig.defconfig
  app/boards/shields/splitreus62/Kconfig.defconfig
  app/dts/bindings/behaviors/one_param.yaml
  app/dts/bindings/behaviors/two_param.yaml
  app/dts/bindings/behaviors/zero_param.yaml
  app/dts/bindings/behaviors/zmk,behavior-bluetooth.yaml
  app/dts/bindings/behaviors/zmk,behavior-ext-power.yaml
  app/dts/bindings/behaviors/zmk,behavior-key-press.yaml
  app/dts/bindings/behaviors/zmk,behavior-momentary-layer.yaml
  app/dts/bindings/behaviors/zmk,behavior-none.yaml
  app/dts/bindings/behaviors/zmk,behavior-outputs.yaml
  app/dts/bindings/behaviors/zmk,behavior-reset.yaml
  app/dts/bindings/behaviors/zmk,behavior-sensor-rotate-key-press.yaml
  app/dts/bindings/behaviors/zmk,behavior-transparent.yaml
  app/dts/bindings/zmk,ext-power-generic.yaml
  app/dts/bindings/zmk,keymap-sensors.yaml
  app/run-test.sh
  app/scripts/west-commands.yml
  app/scripts/west_commands/test.py
  docs/static/setup.ps1
  docs/static/setup.sh
Labels: chore

#561 refactor(shields): standardize README.md filenames
  app/boards/shields/bfo9000/README.md
  app/boards/shields/clueboard_california/README.md
  app/boards/shields/crbn/README.md
  app/boards/shields/eek/README.md
  app/boards/shields/m60/README.md
Labels: refactor, shields

#594 fix(setup.sh): add NIBBLE to options
  docs/static/setup.sh
Labels: bug, shields

#581 Initial simple CODEOWNERS file
  CODEOWNERS
Labels: chore

#595 fix(setup.sh): rename BF0-9000 to BFO-9000
  docs/static/setup.sh
Labels: bug, shields

#504 feat(combos): initial implementation
  app/CMakeLists.txt
  app/Kconfig
  app/dts/bindings/zmk,combos.yaml
  app/src/combo.c
  app/tests/combo/combos-and-holdtaps-0/events.patterns
  app/tests/combo/combos-and-holdtaps-0/keycode_events.snapshot
  app/tests/combo/combos-and-holdtaps-0/native_posix.keymap
  app/tests/combo/combos-and-holdtaps-1/events.patterns
  app/tests/combo/combos-and-holdtaps-1/keycode_events.snapshot
  app/tests/combo/combos-and-holdtaps-1/native_posix.keymap
  app/tests/combo/combos-and-holdtaps-2/events.patterns
  app/tests/combo/combos-and-holdtaps-2/keycode_events.snapshot
  app/tests/combo/combos-and-holdtaps-2/native_posix.keymap
  app/tests/combo/multiple-timeouts/events.patterns
  app/tests/combo/multiple-timeouts/keycode_events.snapshot
  app/tests/combo/multiple-timeouts/native_posix.keymap
  app/tests/combo/overlapping-combos-0/events.patterns
  app/tests/combo/overlapping-combos-0/keycode_events.snapshot
  app/tests/combo/overlapping-combos-0/native_posix.keymap
  app/tests/combo/overlapping-combos-1/events.patterns
  app/tests/combo/overlapping-combos-1/keycode_events.snapshot
  app/tests/combo/overlapping-combos-1/native_posix.keymap
  app/tests/combo/overlapping-combos-2/events.patterns
  app/tests/combo/overlapping-combos-2/keycode_events.snapshot
  app/tests/combo/overlapping-combos-2/native_posix.keymap
  app/tests/combo/overlapping-combos-3/events.patterns
  app/tests/combo/overlapping-combos-3/keycode_events.snapshot
  app/tests/combo/overlapping-combos-3/native_posix.keymap
  app/tests/combo/partially-overlapping-combos/events.patterns
  app/tests/combo/partially-overlapping-combos/keycode_events.snapshot
  app/tests/combo/partially-overlapping-combos/native_posix.keymap
  app/tests/combo/press-release/events.patterns
  app/tests/combo/press-release/keycode_events.snapshot
  app/tests/combo/press-release/native_posix.keymap
  app/tests/combo/press-timeout/events.patterns
  app/tests/combo/press-timeout/keycode_events.snapshot
  app/tests/combo/press-timeout/native_posix.keymap
  app/tests/combo/press1-press2-release1-release2/events.patterns
  app/tests/combo/press1-press2-release1-release2/keycode_events.snapshot
  app/tests/combo/press1-press2-release1-release2/native_posix.keymap
  app/tests/combo/press1-press2-release2-release1/events.patterns
  app/tests/combo/press1-press2-release2-release1/keycode_events.snapshot
  app/tests/combo/press1-press2-release2-release1/native_posix.keymap
  app/tests/combo/press1-release1-press2-release2/events.patterns
  app/tests/combo/press1-release1-press2-release2/keycode_events.snapshot
  app/tests/combo/press1-release1-press2-release2/native_posix.keymap
  app/tests/combo/slowrelease-disabled/events.patterns
  app/tests/combo/slowrelease-disabled/keycode_events.snapshot
  app/tests/combo/slowrelease-disabled/native_posix.keymap
  app/tests/combo/slowrelease-enabled/events.patterns
  app/tests/combo/slowrelease-enabled/keycode_events.snapshot
  app/tests/combo/slowrelease-enabled/native_posix.keymap
  docs/docs/behaviors/combos.md
  docs/docs/intro.md
  docs/sidebars.js
Labels: behaviors, enhancement

#521 refactor(core): define usage page as uint16_t
  app/include/zmk/endpoints.h
  app/include/zmk/events/keycode_state_changed.h
  app/src/endpoints.c
  app/src/hid_listener.c
Labels: core, refactor

#607 Clean up uart0 devicetree, don't enable by default
  app/boards/arm/bluemicro840/bluemicro840_v1.dts
  app/boards/arm/nice_nano/nice_nano.dts
  app/boards/arm/nrf52840_m2/nrf52840_m2.dts
  app/boards/arm/nrfmicro/nrfmicro_11.dts
  app/boards/arm/nrfmicro/nrfmicro_11_flipped.dts
  app/boards/arm/nrfmicro/nrfmicro_13.dts
Labels: board, refactor

#610 chore(core): replace `Pete Johanson` with `The ZMK Contributors`
  app/dts/bindings/behaviors/one_param.yaml
  app/dts/bindings/behaviors/two_param.yaml
  app/dts/bindings/behaviors/zero_param.yaml
  app/dts/bindings/behaviors/zmk,behavior-bluetooth.yaml
  app/dts/bindings/behaviors/zmk,behavior-key-press.yaml
  app/dts/bindings/behaviors/zmk,behavior-momentary-layer.yaml
  app/dts/bindings/behaviors/zmk,behavior-none.yaml
  app/dts/bindings/behaviors/zmk,behavior-reset.yaml
  app/dts/bindings/behaviors/zmk,behavior-transparent.yaml
  app/dts/common/arduino_uno_pro_micro_map.dtsi
Labels: chore

#623 Microdox OLED: Unflipped left side
  app/boards/shields/microdox/microdox.dtsi
  app/boards/shields/microdox/microdox_right.overlay
Labels: bug, displays, shields

#584 docs(hold-tap): mark tapping_term_ms as code
  docs/docs/behaviors/hold-tap.md
Labels: documentation

#543 Implement grave-escape
  app/CMakeLists.txt
  app/dts/behaviors.dtsi
  app/dts/behaviors/gresc.dtsi
  app/dts/bindings/behaviors/zmk,behavior-mod-morph.yaml
  app/include/zmk/hid.h
  app/src/behaviors/behavior_mod_morph.c
  app/src/hid.c
  app/tests/gresc/gresc-press-release/events.patterns
  app/tests/gresc/gresc-press-release/keycode_events.snapshot
  app/tests/gresc/gresc-press-release/native_posix.keymap
  app/tests/gresc/gresc-two-instances/events.patterns
  app/tests/gresc/gresc-two-instances/keycode_events.snapshot
  app/tests/gresc/gresc-two-instances/native_posix.keymap
Labels: behaviors, enhancement

#556 Create a WPM counter and display widget
  app/CMakeLists.txt
  app/Kconfig
  app/include/zmk/display/widgets/wpm_status.h
  app/include/zmk/events/wpm_state_changed.h
  app/include/zmk/wpm.h
  app/src/display/status_screen.c
  app/src/display/widgets/CMakeLists.txt
  app/src/display/widgets/Kconfig
  app/src/display/widgets/wpm_status.c
  app/src/events/wpm_state_changed.c
  app/src/wpm.c
  app/tests/wpm/1-single_keypress/events.patterns
  app/tests/wpm/1-single_keypress/keycode_events.snapshot
  app/tests/wpm/1-single_keypress/native_posix.conf
  app/tests/wpm/1-single_keypress/native_posix.keymap
  app/tests/wpm/2-multiple_keypress/events.patterns
  app/tests/wpm/2-multiple_keypress/keycode_events.snapshot
  app/tests/wpm/2-multiple_keypress/native_posix.conf
  app/tests/wpm/2-multiple_keypress/native_posix.keymap
  app/tests/wpm/behavior_keymap.dtsi
Labels: displays, enhancement

#629 refactor(docs): Move combos under Features.
  docs/docs/features/combos.md
  docs/docs/intro.md
  docs/sidebars.js
Labels: documentation, refactor

#511 docs(sticky keys): document sticky keys and sticky layers
  docs/docs/behaviors/sticky-key.md
  docs/docs/behaviors/sticky-layer.md
  docs/sidebars.js
Labels: behaviors, documentation

#635 fix(behaviors): Updated grsec snapshots for new log format.
  app/tests/gresc/gresc-press-release/keycode_events.snapshot
  app/tests/gresc/gresc-two-instances/keycode_events.snapshot
Labels: behaviors, bug, tests

#630 State Of The Firmware #4
  docs/blog/2021-01-27-zmk-sotf-4.md
Labels: blog, enhancement

#436 Add information on how to update the documentation to the docs
  docs/docs/development/documentation.md
  docs/sidebars.js
Labels: documentation, enhancement

#645 fix(docs): Only show push workflow builds in link
  docs/docs/troubleshooting.md
Labels: bug, documentation

#644 fix(docs): Set description to our tagline
  docs/src/pages/index.js
Labels: documentation, enhancement

#608 docs: remove redundant slash from "docs/"
  docs/docusaurus.config.js
Labels: documentation

#636 Add a missing log_strdup()
  app/src/ble.c
Labels: bluetooth, bug, core

#648 fix(docs): Remove comment about here being four profiles for splits
  docs/docs/behaviors/bluetooth.md
Labels: documentation, enhancement
