Repository zmkfirmware/zmk, pull requests merged in 2021-12, with the labels that each got.

#1042 fix(docs): Make the modifier function examples clearer.
  docs/docs/codes/modifiers.mdx
Labels: documentation, keymaps

#1002 feat(shields) Add Redox Shield Support
  app/boards/shields/redox/Kconfig.defconfig
  app/boards/shields/redox/Kconfig.shield
  app/boards/shields/redox/boards/nice_nano.overlay
  app/boards/shields/redox/redox.conf
  app/boards/shields/redox/redox.dtsi
  app/boards/shields/redox/redox.keymap
  app/boards/shields/redox/redox.zmk.yml
  app/boards/shields/redox/redox_left.overlay
  app/boards/shields/redox/redox_right.overlay
Labels: enhancement, shields

#974 feat: Add Osprette Shield
  app/boards/shields/osprette/Kconfig.defconfig
  app/boards/shields/osprette/Kconfig.shield
  app/boards/shields/osprette/osprette.conf
  app/boards/shields/osprette/osprette.keymap
  app/boards/shields/osprette/osprette.overlay
  app/boards/shields/osprette/osprette.zmk.yml
Labels: enhancement, shields, hacktoberfest-accepted

#1027 Add boardsource5x12
  app/boards/shields/boardsource5x12/Kconfig.defconfig
  app/boards/shields/boardsource5x12/Kconfig.shield
  app/boards/shields/boardsource5x12/boardsource5x12.conf
  app/boards/shields/boardsource5x12/boardsource5x12.keymap
  app/boards/shields/boardsource5x12/boardsource5x12.overlay
  app/boards/shields/boardsource5x12/boardsource5x12.zmk.yml
Labels: enhancement, shields

#806 [New Shield] Murphpad
  app/boards/shields/murphpad/Kconfig.defconfig
  app/boards/shields/murphpad/Kconfig.shield
  app/boards/shields/murphpad/boards/nice_nano.conf
  app/boards/shields/murphpad/boards/nice_nano.overlay
  app/boards/shields/murphpad/murphpad.conf
  app/boards/shields/murphpad/murphpad.keymap
  app/boards/shields/murphpad/murphpad.overlay
  app/boards/shields/murphpad/murphpad.zmk.yml
Labels: enhancement, shields

#1060 fix(shields): Don't enable SSD1306 automatically.
  app/boards/shields/murphpad/Kconfig.defconfig
Labels: bug, displays, shields

#1061 chore: Add a few more items to PR template.
  .github/pull_request_template.md
Labels: chore

#1048 Add support for the Jiran
  app/boards/shields/jiran/Kconfig.defconfig
  app/boards/shields/jiran/Kconfig.shield
  app/boards/shields/jiran/jiran.conf
  app/boards/shields/jiran/jiran.dtsi
  app/boards/shields/jiran/jiran.keymap
  app/boards/shields/jiran/jiran.zmk.yml
  app/boards/shields/jiran/jiran_left.overlay
  app/boards/shields/jiran/jiran_right.overlay
Labels: enhancement, shields

#600 docs(codes): Windows Support: Display Adjustment Commands
  docs/src/data/hid.js
Labels: documentation

#602 docs(codes): Windows Support: Symbols, Operations, and Punctuation
  docs/src/data/hid.js
Labels: documentation

#601 docs(codes): Windows Support: Workflow Commands and Locks
  docs/src/data/hid.js
Labels: documentation

#598 docs(codes): Windows Support: Audio Controls
  docs/src/data/hid.js
Labels: documentation

#597 docs(codes): Windows Support: Language/International Inputs
  docs/src/data/hid.js
Labels: documentation
