Repository zmkfirmware/zmk, pull requests merged in 2021-02, with the labels that each got.

#656 Update new keyboard shield testing documentation.
  docs/docs/development/build-flash.md
  docs/docs/development/new-shield.md
Labels: documentation

#655 behaviors(hold-tap): Implement quick_tap_ms (TAPPING_FORCE_HOLD)
  app/dts/bindings/behaviors/zmk,behavior-hold-tap.yaml
  app/src/behaviors/behavior_hold_tap.c
  app/tests/hold-tap/balanced/5-quick-tap/events.patterns
  app/tests/hold-tap/balanced/5-quick-tap/keycode_events.snapshot
  app/tests/hold-tap/balanced/5-quick-tap/native_posix.keymap
  app/tests/hold-tap/balanced/behavior_keymap.dtsi
  app/tests/hold-tap/hold-preferred/5-quick-tap/events.patterns
  app/tests/hold-tap/hold-preferred/5-quick-tap/keycode_events.snapshot
  app/tests/hold-tap/hold-preferred/5-quick-tap/native_posix.keymap
  app/tests/hold-tap/hold-preferred/behavior_keymap.dtsi
  app/tests/hold-tap/tap-preferred/5-quick-tap/events.patterns
  app/tests/hold-tap/tap-preferred/5-quick-tap/keycode_events.snapshot
  app/tests/hold-tap/tap-preferred/5-quick-tap/native_posix.keymap
  app/tests/hold-tap/tap-preferred/behavior_keymap.dtsi
  docs/docs/behaviors/hold-tap.md
Labels: behaviors, enhancement

#650 Crbn encoder
  app/boards/shields/crbn/crbn.conf
  app/boards/shields/crbn/crbn.keymap
  app/boards/shields/crbn/crbn.overlay
Labels: enhancement, shields

#616 refactor(core): Use /omit-if-no-ref/ for behaviors.
  app/dts/behaviors/bluetooth.dtsi
  app/dts/behaviors/ext_power.dtsi
  app/dts/behaviors/key_press.dtsi
  app/dts/behaviors/layer_tap.dtsi
  app/dts/behaviors/mod_tap.dtsi
  app/dts/behaviors/momentary_layer.dtsi
  app/dts/behaviors/none.dtsi
  app/dts/behaviors/outputs.dtsi
  app/dts/behaviors/reset.dtsi
  app/dts/behaviors/rgb_underglow.dtsi
  app/dts/behaviors/sensor_rotate_key_press.dtsi
  app/dts/behaviors/sticky_key.dtsi
  app/dts/behaviors/to_layer.dtsi
  app/dts/behaviors/toggle_layer.dtsi
  app/dts/behaviors/transparent.dtsi
  app/src/behaviors/behavior_bt.c
  app/src/behaviors/behavior_ext_power.c
  app/src/behaviors/behavior_hold_tap.c
  app/src/behaviors/behavior_none.c
  app/src/behaviors/behavior_outputs.c
  app/src/behaviors/behavior_reset.c
  app/src/behaviors/behavior_rgb_underglow.c
  app/src/behaviors/behavior_sensor_rotate_key_press.c
  app/src/behaviors/behavior_to_layer.c
  app/src/behaviors/behavior_toggle_layer.c
  app/src/behaviors/behavior_transparent.c
Labels: core, enhancement, keymaps

#386 Add pre-commit hooks for clang-format and prettier
  .pre-commit-config.yaml
  CONTRIBUTING.md
Labels: documentation, enhancement

#390 docs: Explain ZMK stays connected to inactive host
  docs/docs/behaviors/bluetooth.md
Labels: documentation, enhancement

#620 Refactor nibble / update to match build docs
  app/boards/shields/nibble/Kconfig.defconfig
  app/boards/shields/nibble/README.md
  app/boards/shields/nibble/boards/nice_nano.conf
  app/boards/shields/nibble/boards/nice_nano.overlay
  app/boards/shields/nibble/boards/proton_c.conf
  app/boards/shields/nibble/nibble.conf
  app/boards/shields/nibble/nibble.keymap
  app/boards/shields/nibble/nibble.overlay
Labels: shields

#680 Fix fault on idle if displays not available.
  app/src/display/main.c
Labels: bug, displays

#675 fix(ext-power): Initialize as soon as settings are available
  app/dts/bindings/zmk,ext-power-generic.yaml
  app/src/ext_power_generic.c
Labels: core, enhancement
