Repository zmkfirmware/zmk, pull requests merged in 2021-07, with the labels that each got.

#869 chore(deps): bump @docusaurus/* to 2.0.0-beta.3
  docs/package-lock.json
  docs/package.json
Labels: dependencies, documentation

#845 docs(setup): replace `zephyr-west-action` with `zmk-docker`
  docs/docs/development/setup.md
Labels: documentation

#744 docs: Fix keymap upgrader
  docs/package-lock.json
  docs/package.json
  docs/src/docusaurus-tree-sitter-plugin/index.js
  docs/static/tree-sitter-devicetree.wasm
  docs/static/tree-sitter.wasm
Labels: dependencies, documentation

#750 feat: Add nrf VDDH battery driver
  app/drivers/sensor/CMakeLists.txt
  app/drivers/sensor/Kconfig
  app/drivers/sensor/battery/CMakeLists.txt
  app/drivers/sensor/battery/Kconfig
  app/drivers/sensor/battery/battery_common.c
  app/drivers/sensor/battery/battery_common.h
  app/drivers/sensor/battery/battery_nrf_vddh.c
  app/drivers/sensor/battery/battery_voltage_divider.c
  app/drivers/sensor/battery_voltage_divider/CMakeLists.txt
  app/drivers/sensor/battery_voltage_divider/Kconfig
  app/drivers/zephyr/dts/bindings/sensor/zmk,battery-nrf-vddh.yaml
Labels: enhancement, sensors
