Repository zmkfirmware/zmk, pull requests merged in 2021-03, with the labels that each got.

#700 fix(logging): remove unnecessary newline
  app/drivers/sensor/battery_voltage_divider/battery_voltage_divider.c
  app/src/kscan.c
Labels: chore

#701 refactor(core): make the event manager a bit easier to read
  app/src/event_manager.c
Labels: core, refactor

#312 feat(docs): Add power profiler
  docs/docusaurus.config.js
  docs/src/components/custom-board-form.js
  docs/src/components/power-estimate.js
  docs/src/css/power-estimate.css
  docs/src/css/power-profiler.css
  docs/src/data/power.js
  docs/src/pages/power-profiler.js
  docs/src/utils/hooks.js
Labels: documentation, enhancement, hacktoberfest-accepted
