Repository zmkfirmware/zmk, pull requests merged in 2021-06, with the labels that each got.

#816 fix(boards): Set nice!60 nRF subfamily for openocd
  app/boards/arm/nice60/board.cmake
Labels: board, bug

#732 Update macos GCC embedded section with brew cmd
  docs/docs/development/setup.md
Labels: documentation

#738 Docs: Add icon legend to the feature matrix
  docs/docs/intro.md
Labels: documentation

#742 Keymap adjustment: fixed right alt and added layer quick tap to the Jian
  app/boards/shields/jian/jian.keymap
Labels: enhancement, shields

#822 fix(docs): Upgrade docusaurus, webpack/loaders.
  docs/docs/codes/applications.mdx
  docs/docs/codes/editing.mdx
  docs/docs/codes/index.mdx
  docs/docs/codes/input-assist.mdx
  docs/docs/codes/keyboard-keypad.mdx
  docs/docs/codes/media.mdx
  docs/docs/codes/power.mdx
  docs/package-lock.json
  docs/package.json
  docs/src/docusaurus-tree-sitter-plugin/index.js
Labels: dependencies, documentation

#826 chore(docs): Bump prettier, and reformat w/ it.
  docs/docs/intro.md
  docs/package-lock.json
  docs/package.json
  docs/src/components/codes/Description.jsx
  docs/src/pages/power-profiler.js
Labels: dependencies, documentation

#833 fix(docs): Add permanent redict to zmk.dev domain.
  docs/netlify.toml
Labels: chore, documentation

#619 Cradio v2
  app/boards/shields/cradio/Kconfig.defconfig
  app/boards/shields/cradio/README.md
  app/boards/shields/cradio/cradio.conf
  app/boards/shields/cradio/cradio.dtsi
  app/boards/shields/cradio/cradio.keymap
  app/boards/shields/cradio/cradio_left.overlay
  app/boards/shields/cradio/cradio_right.conf
  app/boards/shields/cradio/cradio_right.overlay
Labels: enhancement, shields
