Repository zmkfirmware/zmk, pull requests merged in 2022-10, with the labels that each got.

#912 Add nrfmicro_13_52833 support
  app/boards/arm/nrfmicro/Kconfig
  app/boards/arm/nrfmicro/Kconfig.board
  app/boards/arm/nrfmicro/Kconfig.defconfig
  app/boards/arm/nrfmicro/arduino_pro_micro_pins_52833.dtsi
  app/boards/arm/nrfmicro/nrfmicro_13_52833.dts
  app/boards/arm/nrfmicro/nrfmicro_13_52833.yaml
  app/boards/arm/nrfmicro/nrfmicro_13_52833.zmk.yml
  app/boards/arm/nrfmicro/nrfmicro_13_52833_defconfig
  app/boards/arm/nrfmicro/pinmux.c
Labels: enhancement, board

#1481 feat(ble): Default a few configs for DIS GATT svc.
  app/Kconfig
Labels: enhancement, bluetooth

#1480 docs(power profiling): add nice!view
  docs/src/data/power.js
  docs/src/pages/power-profiler.js
Labels: documentation

#1464 fix(displays): Adjust alignment and spacing
  app/src/display/status_screen.c
  app/src/display/widgets/battery_status.c
  app/src/display/widgets/layer_status.c
  app/src/display/widgets/output_status.c
  app/src/display/widgets/wpm_status.c
Labels: displays

#1319 feat(boards): Add nullbits SNAP shield
  app/boards/shields/snap/Kconfig.defconfig
  app/boards/shields/snap/Kconfig.shield
  app/boards/shields/snap/boards/nice_nano.overlay
  app/boards/shields/snap/boards/nice_nano_v2.overlay
  app/boards/shields/snap/snap.conf
  app/boards/shields/snap/snap.dtsi
  app/boards/shields/snap/snap.keymap
  app/boards/shields/snap/snap.zmk.yml
  app/boards/shields/snap/snap_left.overlay
  app/boards/shields/snap/snap_right.overlay
Labels: shields
