Repository zmkfirmware/zmk, pull requests merged in 2022-04, with the labels that each got.

#1128 fix(docs): Improve powershell command for setup script for failure cases
  docs/docs/user-setup.md
Labels: documentation

#1208 refactor(tests): Use GH Actions matrix for tests.
  .github/workflows/test.yml
  app/run-test.sh
Labels: tests, refactor

#1218 feat(docs): Reference conditional layers from the layers behavior page
  docs/docs/behaviors/layers.md
Labels: documentation, enhancement

#1210 feat(shields): Add Hummingbird shield
  app/boards/shields/hummingbird/Kconfig.defconfig
  app/boards/shields/hummingbird/Kconfig.shield
  app/boards/shields/hummingbird/hummingbird.conf
  app/boards/shields/hummingbird/hummingbird.keymap
  app/boards/shields/hummingbird/hummingbird.overlay
  app/boards/shields/hummingbird/hummingbird.zmk.yml
Labels: enhancement, shields

#1214 Document Zephyr 3 build errors
  docs/docs/assets/troubleshooting/keymaps/errorscreen.png
  docs/docs/assets/troubleshooting/keymaps/healthyEDIT.png
  docs/docs/assets/troubleshooting/keymaps/unhealthyEDIT.png
  docs/docs/behaviors/key-press.md
  docs/docs/troubleshooting.md
Labels: documentation, enhancement

#1229 feat(boards): Add BDN9 rev2 RGB support
  app/boards/arm/bdn9/Kconfig.defconfig
  app/boards/arm/bdn9/bdn9_rev2.conf
  app/boards/arm/bdn9/bdn9_rev2.dts
Labels: enhancement, board

#1172 feat(blog): Add SOTF #5.
  docs/blog/2022-04-10-zmk-sotf-5.md
Labels: enhancement, blog

#1227 fix(hid): Use a full valid range for consumer page
  app/include/zmk/hid.h
Labels: bug, hid

#1238 fix: Properly use zmkfirmware Zephyr version.
  app/west.yml
Labels: bug, dependencies

#1239 fix(usb): Spilt HID from core USB, logging fix.
  app/CMakeLists.txt
  app/Kconfig
  app/include/zmk/usb.h
  app/include/zmk/usb_hid.h
  app/src/endpoints.c
  app/src/usb.c
  app/src/usb_hid.c
Labels: bug, core, usb

#1249 fix(docs): Ensure relative links always resolve
  docs/docs/features/displays.md
  docs/docs/intro.md
Labels: documentation

#1247 feat(docs): Add TOC to supported hardware page.
  docs/docs/hardware.mdx
  docs/src/components/hardware-list.tsx
  docs/src/components/hardware-utils.ts
  docs/tsconfig.json
Labels: documentation, enhancement

#1256 fix: Exclude `sof` module to avoid build breakage.
  app/west.yml
Labels: bug, dependencies

#1261 fix(split): Raise split notification stack size.
  app/Kconfig
Labels: bug, split, bluetooth

#1255 refactor(battery): Automatically enable battery drivers
  app/boards/arm/bluemicro840/Kconfig.defconfig
  app/boards/arm/bt60/Kconfig.defconfig
  app/boards/arm/mikoto/Kconfig.defconfig
  app/boards/arm/nice60/Kconfig.defconfig
  app/boards/arm/nice_nano/Kconfig.defconfig
  app/boards/arm/nrfmicro/Kconfig.defconfig
  app/boards/arm/s40nc/Kconfig.defconfig
  app/boards/seeeduino_xiao_ble.conf
  app/drivers/sensor/battery/Kconfig
Labels: sensors

#1187 feat(behaviors): Adding global quick tap
  app/dts/bindings/behaviors/zmk,behavior-hold-tap.yaml
  app/src/behaviors/behavior_hold_tap.c
  app/tests/hold-tap/balanced/8-global-quick-tap/1-basic/events.patterns
  app/tests/hold-tap/balanced/8-global-quick-tap/1-basic/keycode_events.snapshot
  app/tests/hold-tap/balanced/8-global-quick-tap/1-basic/native_posix.keymap
  app/tests/hold-tap/balanced/8-global-quick-tap/2-double-hold/events.patterns
  app/tests/hold-tap/balanced/8-global-quick-tap/2-double-hold/keycode_events.snapshot
  app/tests/hold-tap/balanced/8-global-quick-tap/2-double-hold/native_posix.keymap
  app/tests/hold-tap/balanced/8-global-quick-tap/behavior_keymap.dtsi
  app/tests/hold-tap/hold-preferred/8-global-quick-tap/1-basic/events.patterns
  app/tests/hold-tap/hold-preferred/8-global-quick-tap/1-basic/keycode_events.snapshot
  app/tests/hold-tap/hold-preferred/8-global-quick-tap/1-basic/native_posix.keymap
  app/tests/hold-tap/hold-preferred/8-global-quick-tap/2-double-hold/events.patterns
  app/tests/hold-tap/hold-preferred/8-global-quick-tap/2-double-hold/keycode_events.snapshot
  app/tests/hold-tap/hold-preferred/8-global-quick-tap/2-double-hold/native_posix.keymap
  app/tests/hold-tap/hold-preferred/8-global-quick-tap/behavior_keymap.dtsi
  app/tests/hold-tap/tap-preferred/8-global-quick-tap/1-basic/events.patterns
  app/tests/hold-tap/tap-preferred/8-global-quick-tap/1-basic/keycode_events.snapshot
  app/tests/hold-tap/tap-preferred/8-global-quick-tap/1-basic/native_posix.keymap
  app/tests/hold-tap/tap-preferred/8-global-quick-tap/2-double-hold/events.patterns
  app/tests/hold-tap/tap-preferred/8-global-quick-tap/2-double-hold/keycode_events.snapshot
  app/tests/hold-tap/tap-preferred/8-global-quick-tap/2-double-hold/native_posix.keymap
  app/tests/hold-tap/tap-preferred/8-global-quick-tap/behavior_keymap.dtsi
  app/tests/hold-tap/tap-unless-interrupted/6-global-quick-tap/1-basic/events.patterns
  app/tests/hold-tap/tap-unless-interrupted/6-global-quick-tap/1-basic/keycode_events.snapshot
  app/tests/hold-tap/tap-unless-interrupted/6-global-quick-tap/1-basic/native_posix.keymap
  app/tests/hold-tap/tap-unless-interrupted/6-global-quick-tap/2-double-hold/events.patterns
  app/tests/hold-tap/tap-unless-interrupted/6-global-quick-tap/2-double-hold/keycode_events.snapshot
  app/tests/hold-tap/tap-unless-interrupted/6-global-quick-tap/2-double-hold/native_posix.keymap
  app/tests/hold-tap/tap-unless-interrupted/6-global-quick-tap/behavior_keymap.dtsi
  docs/docs/behaviors/hold-tap.md
Labels: enhancement, behaviors

#1277 fix(docs): Clarify `timeout-ms` for Combos
  docs/docs/features/combos.md
Labels: documentation

#1271 feat(usb): Set default HID interval to 1ms (1000Hz)
  app/Kconfig
Labels: enhancement, usb, hid

#1279 fix(docs): Fix broken links in FAQs
  docs/docs/faq.md
Labels: documentation
