Repository zmkfirmware/zmk, pull requests merged in 2022-07, with the labels that each got.

#1371 fix(docs): Add missing underglow on/off defines
  docs/docs/behaviors/underglow.md
Labels: documentation

#1370 fix(shields): Remove uses of deprecated pro_micro_a/d nodes
  app/boards/shields/a_dux/a_dux.dtsi
  app/boards/shields/cradio/README.md
Labels: shields

#1381 fix(docs): typo fixes on config index.md
  docs/docs/config/index.md
Labels: documentation

#1385 feat(kscan): Kconfig for optional scan delay.
  app/drivers/kscan/Kconfig
  app/drivers/kscan/kscan_gpio_matrix.c
Labels: enhancement, core

#1384 feat(docs): Added behavior queue limit section to macros page
  docs/docs/behaviors/macros.md
  docs/docs/config/behaviors.md
Labels: documentation, enhancement

#1399 fix(docs): typo fixes
  docs/docs/user-setup.md
Labels: documentation

#1403 Change wording in RGB_COLOR_HSB description
  docs/docs/behaviors/underglow.md
Labels: documentation, enhancement, lighting

#1298 fix(docs): Update tap-dance and hold-tap documentation
  docs/docs/assets/hold-tap/case1_2.png
  docs/docs/assets/hold-tap/case1_2.svg
  docs/docs/assets/hold-tap/case_hold_preferred.png
  docs/docs/assets/hold-tap/case_hold_preferred.svg
  docs/docs/assets/hold-tap/comparison.png
  docs/docs/assets/hold-tap/comparison.svg
  docs/docs/assets/tap-dance/timing_diagram.svg
  docs/docs/behaviors/hold-tap.md
  docs/docs/behaviors/layers.md
  docs/docs/behaviors/mod-tap.md
  docs/docs/behaviors/tap-dance.md
Labels: documentation
