Repository zmkfirmware/zmk, pull requests merged in 2022-06, with the labels that each got.

#1326 chore: Bump docusaurus and fix deps issue.
  docs/package-lock.json
  docs/package.json
Labels: documentation, dependencies

#1325 feat(gpio): Add 595 shift register driver.
  app/drivers/gpio/CMakeLists.txt
  app/drivers/gpio/Kconfig
  app/drivers/gpio/Kconfig.595
  app/drivers/gpio/gpio_595.c
  app/drivers/zephyr/dts/bindings/gpio/zmk,gpio-595.yaml
Labels: enhancement, core

#1334 fix: Fixed conf file loading.
  app/cmake/ZephyrBuildConfig.cmake
Labels: bug, core

#1337 fix(docs): Fix acorn dep in package lock file.
  docs/package-lock.json
Labels: bug, documentation

#1084 fix(keymaps): Handle matching `then-layer`s.
  app/src/conditional_layer.c
  app/tests/conditional-layer/same-layer-reached-both-ways/events.patterns
  app/tests/conditional-layer/same-layer-reached-both-ways/keycode_events.snapshot
  app/tests/conditional-layer/same-layer-reached-both-ways/native_posix_64.keymap
  app/tests/conditional-layer/same-layer-reached-differently/events.patterns
  app/tests/conditional-layer/same-layer-reached-differently/keycode_events.snapshot
  app/tests/conditional-layer/same-layer-reached-differently/native_posix_64.keymap
  app/tests/conditional-layer/tri-layer-lt/events.patterns
  app/tests/conditional-layer/tri-layer-lt/keycode_events.snapshot
  app/tests/conditional-layer/tri-layer-lt/native_posix_64.keymap
Labels: bug, keymaps

#1340 fix(split): Raise release events on disconnect.
  app/src/split/bluetooth/central.c
Labels: bug, split, bluetooth

#1025 fix(usb): Correctly detect USB connection status.
  app/src/usb.c
Labels: bug, usb

#1360 feat(shields): Add RGB support to 2% Milk
  app/boards/shields/two_percent_milk/boards/nice_nano.overlay
  app/boards/shields/two_percent_milk/boards/nice_nano_v2.overlay
  app/boards/shields/two_percent_milk/boards/nrfmicro_11.overlay
  app/boards/shields/two_percent_milk/boards/nrfmicro_11_flipped.overlay
  app/boards/shields/two_percent_milk/boards/nrfmicro_13.overlay
  app/boards/shields/two_percent_milk/two_percent_milk.conf
Labels: shields
