Repository zmkfirmware/zmk, pull requests merged in 2022-05, with the labels that each got.

#1283 feat(setup): Disallow split w/ wired controller.
  docs/src/setup-script-generation-plugin/index.js
  docs/src/templates/setup.ps1.mustache
  docs/src/templates/setup.sh.mustache
Labels: split, user configs, usb

#1293 fix(boards): Add flash/settings for XIAO BLE
  app/boards/seeeduino_xiao_ble.conf
Labels: bug, board, bluetooth

#1291 fix(sleep): use pm_power_state_force for proper device power management
  app/src/activity.c
  app/src/ext_power_generic.c
Labels: bug

#1268 feat(docs): Add New Behavior Guide
  docs/docs/development/new-behavior.md
  docs/sidebars.js
Labels: documentation, enhancement, behaviors

#1250 fix(docs): Standardize URLs with no trailing slash
  docs/docusaurus.config.js
Labels: documentation
