Repository zmkfirmware/zmk, pull requests merged in 2022-02, with the labels that each got.

#889 feat(ci): Use metadata for builds
  .github/workflows/build.yml
  app/core-coverage.yml
Labels: enhancement

#990 Add support for Knob Goblin shield
  app/boards/shields/knob_goblin/Kconfig.defconfig
  app/boards/shields/knob_goblin/Kconfig.shield
  app/boards/shields/knob_goblin/knob_goblin.conf
  app/boards/shields/knob_goblin/knob_goblin.keymap
  app/boards/shields/knob_goblin/knob_goblin.overlay
  app/boards/shields/knob_goblin/knob_goblin.zmk.yml
Labels: enhancement, shields

#1126 Add guide to build additional keyboards with GH Action
  docs/docs/customization.md
Labels: documentation

#1127 fix(docs): Fix issues with positional hold-tap example
  docs/docs/behaviors/hold-tap.md
Labels: documentation

#1129 fix(docs): Add `behaviors/key-repeat` to sidebar
  docs/sidebars.js
Labels: documentation

#1134 fix(docs): Remove trailing whitespace (to appease prettier)
  docs/docs/development/new-shield.md
Labels: documentation
