Repository zmkfirmware/zmk, pull requests merged in 2023-12, with the labels that each got.

#2046 feat(ble): Make it possible to use BT_GATT_AUTO_SEC_REQ
  app/src/ble.c
Labels: enhancement, bluetooth

#2049 fix(bt): Passkey entry pairing fixes.
  app/src/ble.c
Labels: bluetooth, refactor

#2053 fix(docs): Fix table for BT_DISC
  docs/docs/behaviors/bluetooth.md
Labels: documentation

#2056 fix(docs): Update outdated information in the hardware page
  docs/docs/hardware.mdx
Labels: documentation

#2024 feat(hid): Add KConfig option for higher NKRO usages
  app/Kconfig
  app/include/zmk/hid.h
  docs/docs/config/system.md
Labels: enhancement, hid

#2032 feat(split): Add is_bonded function to peripherals
  app/include/zmk/split/bluetooth/peripheral.h
  app/src/split/bluetooth/peripheral.c
Labels: enhancement, split

#2060 feat(shields): Add ZMK Uno split setup
  app/boards/shields/zmk_uno/Kconfig.defconfig
  app/boards/shields/zmk_uno/Kconfig.shield
  app/boards/shields/zmk_uno/zmk_uno.dtsi
  app/boards/shields/zmk_uno/zmk_uno.overlay
  app/boards/shields/zmk_uno/zmk_uno_split.dtsi
  app/boards/shields/zmk_uno/zmk_uno_split.keymap
  app/boards/shields/zmk_uno/zmk_uno_split_left.conf
  app/boards/shields/zmk_uno/zmk_uno_split_left.overlay
  app/boards/shields/zmk_uno/zmk_uno_split_right.conf
  app/boards/shields/zmk_uno/zmk_uno_split_right.overlay
Labels: enhancement, shields

#2055 feat(docs): Update behaviors config page
  docs/docs/config/behaviors.md
Labels: documentation

#2005 feat(shields): Allow settings_reset to build with board-only keyboards
  app/boards/shields/settings_reset/settings_reset.overlay
Labels: shields

#2069 refactor(bt): Split security and conn exp. Kconfig
  app/Kconfig
  docs/docs/config/bluetooth.md
Labels: core, bluetooth

#2076 fix(ci): Use unique artifact for test logs
  .github/workflows/ble-test.yml
  .github/workflows/test.yml
Labels: tests, dependencies

#2077 refactor(core): Make low priority queue optional.
  app/CMakeLists.txt
  app/Kconfig
Labels: core, refactor

#2050 feat(blog): Add nodefree-config post for spotlight series
  docs/blog/2023-12-17-nodefree-config.md
Labels: blog

#2079 fix(docs): Fix remark on &bt parameter 2
  docs/docs/behaviors/bluetooth.md
Labels: documentation

#2051 feat(bt): Add test for unauth overwrite.
  app/tests/ble/profiles/overwrite-enabled-reconnect-without-bond-then-output-to-selection/centrals.txt
  app/tests/ble/profiles/overwrite-enabled-reconnect-without-bond-then-output-to-selection/events.patterns
  app/tests/ble/profiles/overwrite-enabled-reconnect-without-bond-then-output-to-selection/nrf52_bsim.conf
  app/tests/ble/profiles/overwrite-enabled-reconnect-without-bond-then-output-to-selection/nrf52_bsim.keymap
  app/tests/ble/profiles/overwrite-enabled-reconnect-without-bond-then-output-to-selection/snapshot.log
Labels: bluetooth, tests
