Repository zmkfirmware/zmk, pull requests merged in 2023-05, with the labels that each got.

#1810 fix(bluetooth): Improved checking for conn status.
  app/src/ble.c
Labels: bug, bluetooth

#1815 refactor(split): fix inconsistency in Kconfig names
  app/include/zmk/ble.h
  app/src/keymap.c
  app/src/split/bluetooth/Kconfig
  app/src/split/bluetooth/central.c
  docs/docs/config/system.md
Labels: bluetooth, refactor

#1571 refactor(kscan): batch GPIO reads by port
  app/drivers/kscan/CMakeLists.txt
  app/drivers/kscan/kscan_gpio.c
  app/drivers/kscan/kscan_gpio.h
  app/drivers/kscan/kscan_gpio_direct.c
  app/drivers/kscan/kscan_gpio_matrix.c
Labels: enhancement, core
