Repository zmkfirmware/zmk, pull requests merged in 2023-07, with the labels that each got.

#1867 fix: Disable battery sensors if reporting is off
  app/Kconfig
  app/drivers/sensor/battery/Kconfig
Labels: core, sensors

#1864 feat(shields): Add splitkb.com Aurora Sofle
  app/boards/shields/splitkb_aurora_sofle/Kconfig.defconfig
  app/boards/shields/splitkb_aurora_sofle/Kconfig.shield
  app/boards/shields/splitkb_aurora_sofle/boards/nice_nano.overlay
  app/boards/shields/splitkb_aurora_sofle/boards/nice_nano_v2.overlay
  app/boards/shields/splitkb_aurora_sofle/splitkb_aurora_sofle.conf
  app/boards/shields/splitkb_aurora_sofle/splitkb_aurora_sofle.dtsi
  app/boards/shields/splitkb_aurora_sofle/splitkb_aurora_sofle.keymap
  app/boards/shields/splitkb_aurora_sofle/splitkb_aurora_sofle.zmk.yml
  app/boards/shields/splitkb_aurora_sofle/splitkb_aurora_sofle_left.overlay
  app/boards/shields/splitkb_aurora_sofle/splitkb_aurora_sofle_right.overlay
Labels: enhancement, shields

#1881 fix(battery): change nRF52 ADC gain
  app/drivers/sensor/battery/battery_nrf_vddh.c
  app/drivers/sensor/battery/battery_voltage_divider.c
Labels: enhancement, sensors
