Repository zmkfirmware/zmk, pull requests merged in 2024-12, with the labels that each got.

#2657 chore(main): release 0.1.0
  .release-please-manifest.json
  CHANGELOG.md
  app/VERSION
Labels: autorelease: pending

#2537 refactor(Kconfig): Extracted designer defaults out into new files
  app/Kconfig
  app/Kconfig.defaults
  app/module/drivers/sensor/ec11/Kconfig
  app/src/split/Kconfig
  app/src/split/Kconfig.defaults
  app/src/split/bluetooth/Kconfig
  app/src/split/bluetooth/Kconfig.defaults
  docs/docs/config/system.md
Labels: refactor

#2651 Add ortho_4x10 grid layout
  app/dts/layouts/common/ortho_4x10/1x2u.dtsi
  app/dts/layouts/common/ortho_4x10/all1u.dtsi
  app/dts/layouts/common/ortho_4x10/position_map.dtsi
Labels: studio

#2702 fix(pointing): Complete header rename missed in refactor
  app/tests/pointing/mkp/native_posix.keymap
  app/tests/pointing/mkp/native_posix_64.conf
  app/tests/pointing/mkp/native_posix_64.keymap
  app/tests/pointing/mouse-move/move_diagonal/native_posix_64.keymap
  app/tests/pointing/mouse-move/move_x/native_posix_64.keymap
  app/tests/pointing/mouse-move/move_y/native_posix_64.keymap
  app/tests/pointing/mouse-move/processors/move_diagonal_scaling/native_posix_64.keymap
  app/tests/pointing/mouse-move/processors/move_diagonal_xy_invert/native_posix_64.keymap
  app/tests/pointing/mouse-move/processors/move_diagonal_xy_swap/native_posix_64.keymap
  app/tests/pointing/mouse-move/processors/temp_layer/1-deactivate-layer-timeout/native_posix_64.keymap
  app/tests/pointing/mouse-move/processors/temp_layer/2a-deactivate-layer-position-trigger/native_posix_64.keymap
  app/tests/pointing/mouse-move/processors/temp_layer/2b-deactivate-layer-position-not-trigger/native_posix_64.keymap
  app/tests/pointing/mouse-move/processors/temp_layer/3-require-prior-idle-ms/native_posix_64.keymap
  docs/docs/keymaps/behaviors/mouse-emulation.md
Labels: bug, pointers

#2682 Fix: allow kscan-composite to wake up device.
  app/dts/bindings/zmk,kscan-composite.yaml
  app/module/drivers/kscan/kscan_composite.c
  docs/docs/config/kscan.md
Labels: core

#2643 fix: Fix warnings in nanopb encoding code
  app/src/studio/behavior_subsystem.c
  app/src/studio/keymap_subsystem.c
Labels: core, studio

#2714 Feature: input processor behavior invocation
  app/dts/bindings/input_processors/zmk,input-processor-behaviors.yaml
  app/dts/input/processors.dtsi
  app/dts/input/processors/behaviors.dtsi
  app/include/drivers/input_processor.h
  app/include/zmk/combos.h
  app/include/zmk/input_listeners.h
  app/include/zmk/virtual_key_position.h
  app/src/pointing/CMakeLists.txt
  app/src/pointing/Kconfig
  app/src/pointing/input_listener.c
  app/src/pointing/input_processor_behaviors.c
  app/src/pointing/input_processor_code_mapper.c
  app/src/pointing/input_processor_scaler.c
  app/src/pointing/input_processor_temp_layer.c
  app/src/pointing/input_processor_transform.c
  app/tests/pointing/mouse-move/processors/behaviors_basic/events.patterns
  app/tests/pointing/mouse-move/processors/behaviors_basic/keycode_events.snapshot
  app/tests/pointing/mouse-move/processors/behaviors_basic/native_posix_64.conf
  app/tests/pointing/mouse-move/processors/behaviors_basic/native_posix_64.keymap
  app/tests/pointing/mouse-move/processors/behaviors_hold_tap/events.patterns
  app/tests/pointing/mouse-move/processors/behaviors_hold_tap/keycode_events.snapshot
  app/tests/pointing/mouse-move/processors/behaviors_hold_tap/native_posix_64.conf
  app/tests/pointing/mouse-move/processors/behaviors_hold_tap/native_posix_64.keymap
  docs/docs/keymaps/input-processors/behaviors.md
  docs/docs/keymaps/input-processors/index.md
Labels: enhancement, pointers

#2711 fix: Kconfig refactor now works correctly with external modules
  app/Kconfig
Labels: bug, refactor

#2718 chore: Docs bullet point in PR checklist
  .github/pull_request_template.md
Labels: chore

#2725 Allow running tests from anywhere and support EXTRA_MODULES
  .github/workflows/test.yml
  app/run-test.sh
Labels: enhancement, core, tests
