Repository zmkfirmware/zmk, pull requests merged in 2024-08, with the labels that each got.

#2390 mini-feat(docs) Improvements to the layer documentation
  docs/docs/behaviors/layers.md
  docs/docs/features/keymaps.mdx
  docs/docs/keymap-example.md
Labels: documentation

#2394 fix(docs): Fix link for matrix transform
  docs/docs/config/kscan.md
Labels: documentation

#2389 fix(docs): Document number of peripherals Kconfig
  docs/docs/config/system.md
Labels: documentation

#2392 fix(docs): Fix toggle layer docs
  docs/docs/behaviors/layers.md
Labels: documentation

#2399 fix(pm): Properly configure a wakeup as input.
  app/src/gpio_key_wakeup_trigger.c
Labels: bug, core

#2402 fix: Proper device PM support for composite kscan.
  app/module/drivers/kscan/kscan_composite.c
Labels: bug, core

#2416 fix: Fix hardware metadata validation after image changes.
  .github/workflows/hardware-metadata-validation.yml
Labels: bug, chore, github_actions

#2411 feat(docs) Minor improvements to the docs
  docs/docs/config/index.md
  docs/docs/troubleshooting/connection-issues.mdx
Labels: documentation

#2418 fix(docs): Fix broken anchor in reset behaviors
  docs/docs/behaviors/reset.md
Labels: documentation

#2415 feat(docs): Add a note on column numbers for DTS errors
  docs/docs/troubleshooting/building-issues.md
Labels: documentation

#2393 fix(docs): Fix mod-morph terms from keycodes to bindings
  docs/docs/behaviors/mod-morph.md
Labels: documentation

#2405 fix: no error return in sticky key get_parameter_metadata
  app/src/behaviors/behavior_sticky_key.c
Labels: bug

#2384 Update pancake url
  app/boards/shields/pancake/pancake.zmk.yml
Labels: shields

#2427 fix(docs): Note direct pin use in matrix transform
  docs/docs/config/kscan.md
Labels: documentation

#2431 feat(docs): Added and modified docs to point users to the experimental zmk-cli.
  docs/docs/user-setup-cli.mdx
  docs/docs/user-setup.mdx
Labels: documentation

#2445 fix(display): widgets: increase buffer size for symbols
  app/src/display/widgets/layer_status.c
  app/src/display/widgets/output_status.c
Labels: displays
