Repository zmkfirmware/zmk, pull requests merged in 2024-09, with the labels that each got.

#2450 fix(docs): Fix broken anchors
  docs/docs/development/new-shield.mdx
  docs/docs/keymaps/behaviors/tap-dance.mdx
Labels: documentation

#2449 chore(deps): npm update on docs
  docs/package-lock.json
Labels: documentation, chore, dependencies

#2438 refactor(docs): refactored the development section
  docs/blog/2021-07-17-zephyr-2-5.md
  docs/blog/2022-04-02-zephyr-3-0.md
  docs/blog/2022-04-10-zmk-sotf-5.md
  docs/blog/2023-04-06-zephyr-3-2.md
  docs/blog/2023-10-05-zmk-sotf-6.md
  docs/blog/2024-02-09-zephyr-3-5.md
  docs/docs/config/index.md
  docs/docs/config/kscan.md
  docs/docs/customization.md
  docs/docs/development/contributing/clean-room.md
  docs/docs/development/contributing/documentation.md
  docs/docs/development/hardware-integration/boards-shields-keymaps.md
  docs/docs/development/hardware-integration/hardware-metadata-files.md
  docs/docs/development/hardware-integration/new-shield.mdx
  docs/docs/development/local-toolchain/build-flash.mdx
  docs/docs/development/local-toolchain/ide-integration.mdx
  docs/docs/development/local-toolchain/posix-board.md
  docs/docs/development/local-toolchain/pre-commit.md
  docs/docs/development/local-toolchain/setup/docker.md
  docs/docs/development/local-toolchain/setup/index.md
  docs/docs/development/local-toolchain/setup/native.mdx
  docs/docs/development/local-toolchain/tests.md
  docs/docs/development/new-behavior.mdx
  docs/docs/development/studio-rpc-protocol.md
  docs/docs/features/encoders.md
  docs/docs/features/modules.mdx
  docs/docs/features/split-keyboards.md
  docs/docs/hardware.mdx
  docs/docs/user-setup-cli.mdx
  docs/docs/user-setup.mdx
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/static/_redirects
Labels: documentation

#2397 feat: Split physical layout selection sync.
  app/include/zmk/physical_layouts.h
  app/include/zmk/split/bluetooth/uuid.h
  app/src/physical_layouts.c
  app/src/split/bluetooth/central.c
  app/src/split/bluetooth/service.c
Labels: enhancement, core, split, bluetooth

#2377 Fix max brightness in backlight metadata
  app/src/behaviors/behavior_backlight.c
Labels: lighting, studio

#2425 Fix path to `run-test.sh` when ZMK is used as a module
  app/scripts/west_commands/test.py
Labels: tests

#2369 refactor(shields): tidbit
  app/boards/shields/tidbit/README.md
  app/boards/shields/tidbit/boards/nice_nano.conf
  app/boards/shields/tidbit/boards/proton_c.conf
  app/boards/shields/tidbit/tidbit.conf
  app/boards/shields/tidbit/tidbit.dtsi
  app/boards/shields/tidbit/tidbit.keymap
  app/boards/shields/tidbit/tidbit.overlay
  app/boards/shields/tidbit/tidbit_19key.conf
  app/boards/shields/tidbit/tidbit_19key.keymap
  app/boards/shields/tidbit/tidbit_19key.overlay
Labels: shields

#2424 fix(boards): add sleep pinctrl node for nice!60
  app/boards/arm/nice60/nice60-pinctrl.dtsi
  app/boards/arm/nice60/nice60.dts
Labels: board

#2460 Update index.mdx: Mention display-name property
  docs/docs/keymaps/index.mdx
Labels: documentation

#2452 feat(docs): Added a page on shift registers
  docs/docs/assets/hardware-integration/shift-register-daisy.png
  docs/docs/development/hardware-integration/shift-registers.md
  docs/sidebars.js
Labels: documentation

#2465 docs(fix): broken anchor in studio setup
  docs/docs/development/hardware-integration/studio-setup.md
Labels: documentation

#2472 fix(bt): Fix compilation failure for clearing bonds.
  app/src/ble.c
Labels: bug, bluetooth

#2481 fix: Fix wakeup from kscan wrapped in sideband.
  app/src/kscan_sideband_behaviors.c
  app/src/physical_layouts.c
Labels: bug, core

#2486 fix: Reduce RAM usage in the keymap
  app/src/keymap.c
Labels: bug, core

#2490 fix(core): Warn only with layouts + chosen transform
  app/include/zmk/matrix.h
  app/src/physical_layouts.c
Labels: bug, core

#2498 chore: Formatting fix.
  app/src/behavior_queue.c
Labels: chore

#2482 feat: Split physical layout selection sync.
  app/include/zmk/physical_layouts.h
  app/include/zmk/split/bluetooth/uuid.h
  app/src/physical_layouts.c
  app/src/split/bluetooth/central.c
  app/src/split/bluetooth/service.c
Labels: enhancement, split, studio

#2335 feat(ble): Set device name at runtime
  app/Kconfig
  app/include/zmk/ble.h
  app/src/ble.c
  app/tests/ble/profiles/bond-clear-then-bond-second-client/snapshot.log
  app/tests/ble/profiles/bond-to-cleared-profile/snapshot.log
  app/tests/ble/profiles/connnect-and-output-to-selection/snapshot.log
  app/tests/ble/profiles/dont-bond-to-taken-profile/snapshot.log
  app/tests/ble/profiles/first-and-second-profile-paired-then-send-data/snapshot.log
  app/tests/ble/profiles/overwrite-enabled-reconnect-without-bond-then-output-to-selection/snapshot.log
  app/tests/ble/profiles/reconnect-then-output-to-selection/snapshot.log
  app/tests/ble/security/read-hid-after-connect-with-auto-sec/snapshot.log
  app/tests/ble/security/read-hid-after-connect-without-auto-sec/snapshot.log
Labels: core, bluetooth

#2504 chore: Fix keymap const warning.
  app/src/keymap.c
Labels: core, chore

#2507 fix: Force Ubuntu 22.04, pending CI fixes.
  .github/workflows/build-user-config.yml
Labels: bug, user configs

#2509 docs: Added a note on bluetooth profiles under "unable to connect to device"
  docs/docs/troubleshooting/connection-issues.mdx
Labels: documentation

#2510 docs: Pulled the encoders section of the new shield guide out into its own page
  docs/docs/development/hardware-integration/encoders.md
  docs/docs/development/hardware-integration/new-shield.mdx
  docs/docs/features/encoders.md
  docs/sidebars.js
Labels: documentation

#2515 docs: Streamlined the new shield guide
  docs/docs/development/hardware-integration/new-shield.mdx
  docs/docs/keymap-example-file.md
Labels: documentation
