Repository zmkfirmware/zmk, pull requests merged in 2024-01, with the labels that each got.

#2045 feat(ble): Support peripheral battery levels.
  app/include/zmk/events/battery_state_changed.h
  app/include/zmk/split/bluetooth/central.h
  app/src/display/widgets/battery_status.c
  app/src/events/battery_state_changed.c
  app/src/split/bluetooth/CMakeLists.txt
  app/src/split/bluetooth/Kconfig
  app/src/split/bluetooth/central.c
  app/src/split/bluetooth/central_bas_proxy.c
  docs/docs/config/system.md
Labels: enhancement, split, bluetooth

#2092 feat(blog): Add post for joelspadin projects for spotlight series
  docs/blog/2024-01-05-zmk-tools.md
Labels: blog

#2091 Fix high idle/sleep current due to flash and use xiao-ble from upstream Zephyr
  app/boards/seeeduino_xiao_ble.overlay
Labels: bug, board

#2094 fix: Fix function signatures for WPM.
  app/src/wpm.c
Labels: core, chore

#2097 fix(split): Split peripherals should auto sec req still.
  app/Kconfig
Labels: bug, split, bluetooth

#2098 fix(boards): Fix up EXT_POWER naming for adv360pro;
  app/boards/arm/adv360pro/adv360pro.dtsi
Labels: bug, board

#2111 chore(ci): Split build and upload into separate steps
  .github/workflows/build.yml
Labels: chore, refactor

#2113 fix: Fix missed event manager usages from refactor.
  app/src/hid_indicators.c
  app/src/split/bluetooth/central.c
  app/src/split/bluetooth/service.c
Labels: bug, refactor

#2120 fix(shields): Fix battery warnings for custom widgets.
  app/boards/shields/nice_view/widgets/peripheral_status.c
  app/boards/shields/nice_view/widgets/status.c
Labels: displays, chore

#2134 fix(ci): Use proper variable expression.
  .github/workflows/build.yml
Labels: bug

#2136 fix(ci): Update one lingering upload-artifacts action.
  .github/workflows/build-user-config.yml
Labels: dependencies
