Repository zmkfirmware/zmk, pull requests merged in 2024-05, with the labels that each got.

#2289 fix: Initialize sideband kscan in APPLICATION.
  app/src/kscan_sideband_behaviors.c
Labels: bug, core

#2292 feat(docs): Document example toggle-mode implementation
  docs/docs/config/kscan.md
Labels: documentation

#1965 feat(boards): Add nRF52 high voltage DC/DC config
  app/boards/arm/mikoto/Kconfig
  app/boards/arm/nice_nano/Kconfig
Labels: board
