Repository zmkfirmware/zmk, pull requests merged in 2024-06, with the labels that each got.

#2272 feat(docs): Improve the toolchain setup page
  docs/blog/2020-08-12-zmk-sotf-1.md
  docs/blog/2021-07-17-zephyr-2-5.md
  docs/blog/2022-04-02-zephyr-3-0.md
  docs/blog/2022-04-10-zmk-sotf-5.md
  docs/blog/2023-04-06-zephyr-3-2.md
  docs/blog/2024-02-09-zephyr-3-5.md
  docs/docs/behaviors/index.mdx
  docs/docs/customization.md
  docs/docs/development/new-shield.mdx
  docs/docs/development/setup.mdx
  docs/docs/development/setup/docker.md
  docs/docs/development/setup/index.md
  docs/docs/development/setup/native.mdx
  docs/docs/troubleshooting.md
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/src/css/custom.css
Labels: documentation

#2336 refactor: Remove static CDC ACM logging nodes.
  app/boards/01space_rp2040_042lcd.overlay
  app/boards/adafruit_kb2040.overlay
  app/boards/adafruit_qt_py_rp2040.overlay
  app/boards/arm/adv360pro/adv360pro.dtsi
  app/boards/arm/bdn9/bdn9_rev2.dts
  app/boards/arm/bluemicro840/bluemicro840_v1.dts
  app/boards/arm/bt60/bt60.dtsi
  app/boards/arm/ckp/ckp.dtsi
  app/boards/arm/corneish_zen/corneish_zen.dtsi
  app/boards/arm/dz60rgb/dz60rgb_rev1.dts
  app/boards/arm/ferris/ferris_rev02.dts
  app/boards/arm/glove80/glove80.dtsi
  app/boards/arm/kbdfans_tofu65/kbdfans_tofu65_v2.dts
  app/boards/arm/mikoto/mikoto_520.dts
  app/boards/arm/nice60/nice60.dts
  app/boards/arm/nice_nano/nice_nano.dtsi
  app/boards/arm/nrf52840_m2/nrf52840_m2.dts
  app/boards/arm/nrfmicro/nrfmicro_11.dts
  app/boards/arm/nrfmicro/nrfmicro_11_flipped.dts
  app/boards/arm/nrfmicro/nrfmicro_13.dts
  app/boards/arm/nrfmicro/nrfmicro_13_52833.dts
  app/boards/arm/pillbug/pillbug.dts
  app/boards/arm/planck/planck_rev6.dts
  app/boards/arm/preonic/preonic_rev3.dts
  app/boards/arm/proton_c/proton_c.dts
  app/boards/arm/puchi_ble/puchi_ble_v1.dts
  app/boards/arm/s40nc/s40nc.dts
  app/boards/boardsource_blok.overlay
  app/boards/rpi_pico.overlay
  app/boards/seeeduino_xiao.overlay
  app/boards/seeeduino_xiao_ble.overlay
  app/boards/seeeduino_xiao_rp2040.overlay
  app/boards/sparkfun_pro_micro_rp2040.overlay
  app/boards/usb_console.dtsi
  docs/docs/development/usb-logging.mdx
Labels: core, refactor

#2342 fix(usb): Ensure USB init is last
  app/Kconfig
  app/src/usb_hid.c
Labels: bug, usb

#2345 fix: Actually add the `zmk-usb-logging` snippet.
  app/snippets/zmk-usb-logging/snippet.yml
  app/snippets/zmk-usb-logging/zmk-usb-logging.conf
  app/snippets/zmk-usb-logging/zmk-usb-logging.overlay
Labels: bug, core

#2231 feat(behaviors): Add behavior metadata information.
  app/Kconfig.behaviors
  app/dts/behaviors/backlight.dtsi
  app/dts/behaviors/bluetooth.dtsi
  app/dts/behaviors/caps_word.dtsi
  app/dts/behaviors/ext_power.dtsi
  app/dts/behaviors/gresc.dtsi
  app/dts/behaviors/key_press.dtsi
  app/dts/behaviors/key_repeat.dtsi
  app/dts/behaviors/key_toggle.dtsi
  app/dts/behaviors/layer_tap.dtsi
  app/dts/behaviors/mod_tap.dtsi
  app/dts/behaviors/momentary_layer.dtsi
  app/dts/behaviors/none.dtsi
  app/dts/behaviors/outputs.dtsi
  app/dts/behaviors/reset.dtsi
  app/dts/behaviors/rgb_underglow.dtsi
  app/dts/behaviors/sticky_key.dtsi
  app/dts/behaviors/to_layer.dtsi
  app/dts/behaviors/toggle_layer.dtsi
  app/dts/behaviors/transparent.dtsi
  app/dts/bindings/behaviors/behavior-metadata.yaml
  app/dts/bindings/behaviors/one_param.yaml
  app/dts/bindings/behaviors/two_param.yaml
  app/dts/bindings/behaviors/zero_param.yaml
  app/include/drivers/behavior.h
  app/include/zmk/behavior.h
  app/src/behavior.c
  app/src/behaviors/behavior_backlight.c
  app/src/behaviors/behavior_bt.c
  app/src/behaviors/behavior_hold_tap.c
  app/src/behaviors/behavior_key_press.c
  app/src/behaviors/behavior_key_toggle.c
  app/src/behaviors/behavior_macro.c
  app/src/behaviors/behavior_momentary_layer.c
  app/src/behaviors/behavior_none.c
  app/src/behaviors/behavior_outputs.c
  app/src/behaviors/behavior_rgb_underglow.c
  app/src/behaviors/behavior_soft_off.c
  app/src/behaviors/behavior_sticky_key.c
  app/src/behaviors/behavior_tap_dance.c
  app/src/behaviors/behavior_to_layer.c
  app/src/behaviors/behavior_toggle_layer.c
Labels: enhancement, behaviors, studio

#2346 chore: Add rp2040/USB logging core coverage.
  app/core-coverage.yml
Labels: core

#2347 fix: Add metadata to missed behaviors.
  app/src/behaviors/behavior_caps_word.c
  app/src/behaviors/behavior_key_repeat.c
  app/src/behaviors/behavior_mod_morph.c
  app/src/behaviors/behavior_reset.c
  app/src/behaviors/behavior_transparent.c
Labels: enhancement, studio

#2349 feat(core): Support adding subs to other listeners.
  app/include/zmk/event_manager.h
Labels: enhancement, core

#2350 refactor(ble): Extract API to get active profile connection.
  app/include/zmk/ble.h
  app/src/ble.c
  app/src/hog.c
Labels: enhancement, core, bluetooth

#2348 feat(behaviors): Add local ID system for behaviors
  app/CMakeLists.txt
  app/Kconfig.behaviors
  app/include/drivers/behavior.h
  app/include/linker/zmk-behavior-local-id-map.ld
  app/include/zmk/behavior.h
  app/src/behavior.c
Labels: enhancement, behaviors, studio

#2351 fix: BLE refactor mouse keys fix.
  app/core-coverage.yml
  app/src/hog.c
Labels: bug, bluetooth
