Repository zmkfirmware/zmk, pull requests merged in 2024-03, with the labels that each got.

#2195 fix(build): Properly board revision keymaps.
  app/keymap-module/modules/modules.cmake
Labels: board, keymaps

#2211 chore(docs): fix hold-tap info callout
  docs/docs/behaviors/hold-tap.mdx
Labels: documentation

#2212 feat(docs): Add troubleshooting section for empty_file error
  docs/docs/troubleshooting.md
Labels: documentation

#2214 fix: Add settings reset on start init priority.
  app/Kconfig
  app/src/settings/reset_settings_on_start.c
Labels: bug

#2179 feat(docs): Add a note on using BT with dual boot systems
  docs/docs/features/bluetooth.md
Labels: documentation

#2204 feat: Add ability to fetch battery voltage.
  app/Kconfig
  app/src/battery.c
Labels: enhancement, sensors

#2193 feat(docs): Add Behavior overview page
  docs/docs/behaviors/index.mdx
  docs/sidebars.js
Labels: documentation

#2225 refactor(docs): Refer to overview page for behaviors
  docs/docs/development/new-behavior.mdx
  docs/docs/development/new-shield.mdx
  docs/docs/features/keymaps.mdx
Labels: documentation

#2224 feat(build): Allow specifying snippets for a build.
  .github/workflows/build-user-config.yml
Labels: user configs

#2229 fix(build): Modify function return type to remove compiler warning
  app/src/behaviors/behavior_sticky_key.c
Labels: bug, behaviors

#2234 fix(docs): Add `&soft_off` to behaviors index.
  docs/docs/behaviors/index.mdx
Labels: documentation, behaviors

#2239 fix(docs): Fix bindings types in behaviors config page
  docs/docs/config/behaviors.md
Labels: documentation
