Repository zmkfirmware/zmk, pull requests merged in 2024-11, with the labels that each got.

#2603 fix(studio): Bump nanopb version with build fixes.
  app/west.yml
Labels: bug, studio

#2330 feat(docs) Adding some additional clarity around low power states
  docs/docs/config/kscan.md
  docs/docs/config/power.md
  docs/docs/development/hardware-integration/includes/_gpio-key-direct.md
  docs/docs/development/hardware-integration/includes/_gpio-key-matrix.md
  docs/docs/development/hardware-integration/includes/_gpio-key-wakeup.md
  docs/docs/development/hardware-integration/includes/_sideband-direct.md
  docs/docs/development/hardware-integration/includes/_sideband-matrix.md
  docs/docs/development/hardware-integration/includes/_sideband-wakeup-direct.md
  docs/docs/development/hardware-integration/includes/_soft-off-behavior.md
  docs/docs/development/hardware-integration/includes/_soft-off-waker.md
  docs/docs/development/hardware-integration/soft-off-setup.mdx
  docs/docs/features/low-power-states.md
  docs/docs/features/soft-off.md
  docs/docs/keymaps/behaviors/soft-off.md
  docs/sidebars.js
Labels: documentation

#2605 docs: Add retro-tap sentence and fix anchor
  docs/docs/keymaps/behaviors/hold-tap.mdx
  docs/docs/troubleshooting/connection-issues.mdx
Labels: documentation

#2485 docs(feat): further generalize RGB information
  docs/docs/features/underglow.md
Labels: documentation

#1595 Set C_AL_CALC for macOS and iOS to false
  docs/src/data/hid.js
Labels: documentation

#2574 feat(boards): Add numpad layouts
  app/dts/layouts/common/numpad/17_key.dtsi
  app/dts/layouts/common/numpad/18_key.dtsi
  app/dts/layouts/common/numpad/18_key_00.dtsi
  app/dts/layouts/common/numpad/19_key_00.dtsi
  app/dts/layouts/common/numpad/20_key.dtsi
  app/dts/layouts/common/numpad/21_key.dtsi
  app/dts/layouts/common/numpad/22_key.dtsi
  app/dts/layouts/common/numpad/22_key_00.dtsi
  app/dts/layouts/common/numpad/23_key_00.dtsi
  app/dts/layouts/common/numpad/24_key.dtsi
  app/dts/layouts/common/numpad/position_map.dtsi
Labels: studio

#2626 docs: Fix typos in local-toolchain/setup
  docs/docs/development/local-toolchain/setup/container.mdx
Labels: documentation

#2614 chore: Config dependabot for grouped npm updates
  .github/dependabot.yml
Labels: chore

#2630 fix: Fix inconsistent column offset property
  app/boards/arm/ferris/ferris_rev02.dts
  app/boards/shields/snap/snap_right.overlay
  app/dts/bindings/zmk,kscan-composite.yaml
  app/module/drivers/kscan/kscan_composite.c
  docs/docs/config/kscan.md
Labels: core

#2628 fix: Disable display feature for settings_reset
  app/boards/shields/settings_reset/settings_reset.conf
Labels: shields

#2623 ci: Add gitlint and document commit conventions
  .gitlint
  .pre-commit-config.yaml
  docs/docs/development/contributing/commit-messages.md
  docs/docs/development/local-toolchain/pre-commit.md
  docs/sidebars.js
Labels: github_actions

#2644 docs: Mention build.yaml in Studio instructions
  docs/docs/features/studio.md
Labels: documentation

#2648 feat(drivers): Support init high/low in 595 driver
  app/module/drivers/gpio/gpio_595.c
Labels: enhancement, core

#2622 feat(ci): Add release-please automation with VERSION
  .github/pull_request_template.md
  .github/workflows/release-please.yml
  .pre-commit-config.yaml
  .release-please-manifest.json
  app/VERSION
  docs/docs/development/contributing/pull-requests.md
  docs/sidebars.js
  release-please-config.json
Labels: enhancement, github_actions

#2659 docs(ci): Netlify ignore command to check branch
  docs/netlify-ignore-command.sh
  docs/netlify.toml
Labels: documentation

#2639 docs: move layer defines to reduce confusion
  docs/docs/keymaps/behaviors/layers.md
Labels: documentation

#2594 feat(boards): Add glove80 nexus node for extension GPIO.
  app/boards/arm/glove80/glove80_lh.dts
  app/boards/arm/glove80/glove80_rh.dts
  app/dts/bindings/gpio/moergo,glove80-ext.yaml
  app/dts/bindings/vendor-prefixes.txt
Labels: board

#2672 fix(boards): Disable uart serial node in Xiao BLE by default
  app/boards/seeeduino_xiao_ble.overlay
Labels: board

#2677 docs: Mention combos in reset behaviors
  docs/docs/keymaps/behaviors/reset.md
Labels: documentation

#2634 docs: Create a Hardware Integration index page
  docs/docs/development/hardware-integration/boards-shields-keymaps.md
  docs/docs/development/hardware-integration/index.mdx
  docs/docs/faq.md
  docs/docs/hardware.mdx
  docs/sidebars.js
Labels: documentation
