Repository zmkfirmware/zmk, pull requests merged in 2024-07, with the labels that each got.

#2352 fix: Adjust hid indicator listeners for event refactor
  app/src/hid_indicators.c
Labels: bug, hid

#2358 fix: Improve startup time with proper settings loading.
  app/Kconfig.behaviors
  app/include/zmk/behavior.h
  app/src/backlight.c
  app/src/behavior.c
  app/src/ble.c
  app/src/endpoints.c
  app/src/ext_power_generic.c
  app/src/main.c
  app/src/rgb_underglow.c
  app/src/split/bluetooth/central.c
  app/src/split/bluetooth/peripheral.c
Labels: bug, core

#2323 feat(boards): Add flash/settings to XIAO RP2040.
  app/boards/seeeduino_xiao_rp2040.conf
  app/boards/seeeduino_xiao_rp2040.overlay
Labels: enhancement, board

#2362 fix: Fix external power settings load issue.
  app/src/ext_power_generic.c
Labels: bug, core

#2366 fix: Proper behavior metadata for key repeat/toggle
  app/src/behaviors/behavior_key_repeat.c
  app/src/behaviors/behavior_key_toggle.c
Labels: bug, behaviors, studio

#2371 fix(docs): Add required display-name in physical layout examples
  docs/docs/development/new-shield.mdx
Labels: documentation

#2387 mini-feat(docs) Troubleshooting: Added a note on the experimental bluetooth connection options
  docs/docs/config/bluetooth.md
  docs/docs/troubleshooting/connection-issues.mdx
Labels: documentation

#2381 chore(vscode) Added a recommended extension for .mdx files
  .vscode/extensions.json
Labels: chore

#2380 feat(docs) Adding some clarity around ZMK modules
  docs/docs/config/index.md
  docs/docs/development/build-flash.mdx
  docs/docs/development/new-shield.mdx
  docs/docs/features/beta-testing.mdx
  docs/docs/features/modules.mdx
  docs/sidebars.js
Labels: documentation
