Repository zmkfirmware/zmk, pull requests merged in 2025-01, with the labels that each got.

#2737 Testing: Add spilt BLE tests
  app/run-ble-test.sh
  app/src/ble.c
  app/tests/ble/profiles/bond-clear-then-bond-second-client/siblings.txt
  app/tests/ble/profiles/bond-to-cleared-profile/siblings.txt
  app/tests/ble/profiles/connnect-and-output-to-selection/siblings.txt
  app/tests/ble/profiles/dont-bond-to-taken-profile/siblings.txt
  app/tests/ble/profiles/first-and-second-profile-paired-then-send-data/siblings.txt
  app/tests/ble/profiles/overwrite-enabled-reconnect-without-bond-then-output-to-selection/siblings.txt
  app/tests/ble/profiles/reconnect-then-output-to-selection/siblings.txt
  app/tests/ble/security/read-hid-after-connect-with-auto-sec/siblings.txt
  app/tests/ble/security/read-hid-after-connect-without-auto-sec/siblings.txt
  app/tests/ble/split/basic/events.patterns
  app/tests/ble/split/basic/nrf52_bsim.conf
  app/tests/ble/split/basic/nrf52_bsim.keymap
  app/tests/ble/split/basic/peripheral.overlay
  app/tests/ble/split/basic/siblings.txt
  app/tests/ble/split/basic/snapshot.log
  app/tests/ble/split/multiple-peripherals/events.patterns
  app/tests/ble/split/multiple-peripherals/nrf52_bsim.conf
  app/tests/ble/split/multiple-peripherals/nrf52_bsim.keymap
  app/tests/ble/split/multiple-peripherals/peripheral1.overlay
  app/tests/ble/split/multiple-peripherals/peripheral2.overlay
  app/tests/ble/split/multiple-peripherals/siblings.txt
  app/tests/ble/split/multiple-peripherals/snapshot.log
  app/tests/ble/split/run-peripheral-behavior/events.patterns
  app/tests/ble/split/run-peripheral-behavior/nrf52_bsim.conf
  app/tests/ble/split/run-peripheral-behavior/nrf52_bsim.keymap
  app/tests/ble/split/run-peripheral-behavior/peripheral.overlay
  app/tests/ble/split/run-peripheral-behavior/siblings.txt
  app/tests/ble/split/run-peripheral-behavior/snapshot.log
Labels: split, bluetooth, tests

#2739 fix(combos): Properly report combos len with emply block
  app/include/zmk/combos.h
  app/tests/pointing/mouse-move/processors/behaviors_hold_tap/native_posix_64.keymap
Labels: bug, combos

#2747 test(split): Test split HID indicator setting.
  app/tests/ble/central/src/main.c
  app/tests/ble/split/set-hid-indicators/events.patterns
  app/tests/ble/split/set-hid-indicators/nrf52_bsim.conf
  app/tests/ble/split/set-hid-indicators/nrf52_bsim.keymap
  app/tests/ble/split/set-hid-indicators/peripheral.overlay
  app/tests/ble/split/set-hid-indicators/siblings.txt
  app/tests/ble/split/set-hid-indicators/snapshot.log
Labels: enhancement, split, tests

#2748 fix(studio): Allow adding layers after a layer move
  app/src/studio/keymap_subsystem.c
Labels: bug, studio

#2703 docs: Improve pointing docs
  docs/docs/config/pointing.md
  docs/docs/development/hardware-integration/pointing.mdx
  docs/docs/keymaps/behaviors/mouse-emulation.md
  docs/docs/keymaps/input-processors/index.md
  docs/docs/keymaps/input-processors/transformer.md
Labels: documentation

#2754 Testing: split ble encoder test
  app/module/drivers/sensor/CMakeLists.txt
  app/module/drivers/sensor/Kconfig
  app/module/drivers/sensor/encoder_mock/CMakeLists.txt
  app/module/drivers/sensor/encoder_mock/Kconfig
  app/module/drivers/sensor/encoder_mock/encoder_mock.c
  app/module/dts/bindings/sensor/zmk,sensor-encoder-mock.yaml
  app/tests/ble/split/peripheral-encoder/events.patterns
  app/tests/ble/split/peripheral-encoder/nrf52_bsim.conf
  app/tests/ble/split/peripheral-encoder/nrf52_bsim.keymap
  app/tests/ble/split/peripheral-encoder/peripheral.overlay
  app/tests/ble/split/peripheral-encoder/shared.dtsi
  app/tests/ble/split/peripheral-encoder/siblings.txt
  app/tests/ble/split/peripheral-encoder/snapshot.log
Labels: split, bluetooth, tests

#2764 docs: Fix broken anchors in dongle page
  docs/docs/development/hardware-integration/dongle.mdx
Labels: documentation

#2704 docs: Move more sections under hardware integration
  docs/blog/2020-08-12-zmk-sotf-1.md
  docs/blog/2022-04-02-zephyr-3-0.md
  docs/blog/2022-04-10-zmk-sotf-5.md
  docs/blog/2023-10-05-zmk-sotf-6.md
  docs/docs/config/backlight.md
  docs/docs/config/lighting.md
  docs/docs/development/hardware-integration/battery.md
  docs/docs/development/hardware-integration/lighting/backlight.mdx
  docs/docs/development/hardware-integration/lighting/index.mdx
  docs/docs/development/hardware-integration/lighting/underglow.md
  docs/docs/features/battery.md
  docs/docs/features/lighting.md
  docs/docs/intro.md
  docs/docs/keymaps/behaviors/backlight.md
  docs/docs/keymaps/behaviors/underglow.md
  docs/sidebars.js
  docs/static/_redirects
Labels: documentation

#2769 fix(drivers): Proper static/const for data/config
  app/module/drivers/display/il0323.c
  app/module/drivers/gpio/gpio_595.c
  app/module/drivers/gpio/gpio_max7318.c
  app/module/drivers/input/input_mock.c
  app/module/drivers/kscan/kscan_gpio_charlieplex.c
  app/module/drivers/kscan/kscan_gpio_direct.c
  app/module/drivers/kscan/kscan_gpio_matrix.c
  app/module/drivers/sensor/ec11/ec11.c
  app/module/drivers/sensor/max17048/max17048.c
Labels: core, refactor

#2770 feat(core): Make physical layout key rotation optional
  app/Kconfig
  app/include/zmk/physical_layouts.h
  app/src/physical_layouts.c
  app/src/studio/keymap_subsystem.c
  docs/docs/config/layout.md
Labels: enhancement, refactor, studio

#2771 refactor(keymap): Reduce flash usage for studio builds
  app/include/zmk/keymap.h
  app/src/keymap.c
Labels: refactor, studio

#2788 docs: Update dongle FAQ entry
  docs/docs/faq.md
Labels: documentation

#2767 docs: Update intro page
  docs/docs/intro.md
  docs/docs/intro.mdx
  docs/src/components/columns.tsx
  docs/src/css/custom.css
Labels: documentation

#2790 docs: Update keymaps index intro
  docs/docs/assets/features/keymaps/layer-diagram.png
  docs/docs/assets/keymaps/layer-diagram.png
  docs/docs/keymaps/index.mdx
Labels: documentation

#2796 docs: Add pointers to final Kconfig/devicetree files
  docs/docs/assets/troubleshooting/building/devicetree-step.png
  docs/docs/assets/troubleshooting/building/kconfig-step.png
  docs/docs/config/index.md
  docs/docs/troubleshooting/building-issues.md
Labels: documentation
