Repository zmkfirmware/zmk, pull requests merged in 2025-03, with the labels that each got.

#2693 chore(main): release 0.2.0
  .release-please-manifest.json
  CHANGELOG.md
  app/VERSION
Labels: autorelease: pending

#2850 fix(behaviors): Proper comma separated device list
  app/src/behaviors/behavior_caps_word.c
  app/src/behaviors/behavior_key_repeat.c
Labels: bug, behaviors

#2851 chore(main): release 0.2.1
  .release-please-manifest.json
  CHANGELOG.md
  app/VERSION
Labels: autorelease: pending

#2861 docs: Fix wakeup-source property location for composite kscan
  docs/docs/config/kscan.md
Labels: documentation

#2879 docs: Fix powershell tab in user setup
  docs/docs/user-setup.mdx
Labels: documentation

#2878 chore(deps): npm update on docs
  docs/package-lock.json
Labels: documentation, chore, dependencies

#2766 Feature: Full-Duplex Wired Split
  app/Kconfig
  app/Kconfig.defaults
  app/boards/arm/glove80/Kconfig.defconfig
  app/boards/shields/zmk_uno/zmk_uno_split.dtsi
  app/dts/bindings/zmk,wired-split.yaml
  app/include/linker/zmk-split-transport-central.ld
  app/include/linker/zmk-split-transport-peripheral.ld
  app/include/zmk/ble.h
  app/include/zmk/split/bluetooth/central.h
  app/include/zmk/split/bluetooth/service.h
  app/include/zmk/split/central.h
  app/include/zmk/split/peripheral.h
  app/include/zmk/split/transport/central.h
  app/include/zmk/split/transport/peripheral.h
  app/include/zmk/split/transport/types.h
  app/src/behavior.c
  app/src/ble.c
  app/src/hid_indicators.c
  app/src/pointing/input_split.c
  app/src/split/CMakeLists.txt
  app/src/split/Kconfig
  app/src/split/Kconfig.defaults
  app/src/split/bluetooth/CMakeLists.txt
  app/src/split/bluetooth/central.c
  app/src/split/bluetooth/central_bas_proxy.c
  app/src/split/bluetooth/service.c
  app/src/split/bluetooth/split_listener.c
  app/src/split/central.c
  app/src/split/peripheral.c
  app/src/split/wired/CMakeLists.txt
  app/src/split/wired/Kconfig
  app/src/split/wired/Kconfig.defaults
  app/src/split/wired/central.c
  app/src/split/wired/peripheral.c
  app/src/split/wired/wired.c
  app/src/split/wired/wired.h
  app/tests/ble/split/run-peripheral-behavior/snapshot.log
  docs/docs/config/battery.md
  docs/docs/config/split.md
  docs/docs/config/system.md
  docs/docs/development/hardware-integration/new-shield.mdx
  docs/docs/faq.md
  docs/docs/features/split-keyboards.md
  docs/sidebars.js
Labels: enhancement, split

#2884 fix(split): Conditionally build all split code
  app/CMakeLists.txt
Labels: bug, split

#2895 docs: Document missing user-defined input processors
  docs/docs/keymaps/input-processors/index.md
Labels: documentation

#2890 blog: Add meeting notes from February
  docs/blog/2025-03-20-contributor-sync-1.md
  docs/blog/authors.yml
Labels: blog
