Repository zmkfirmware/zmk, pull requests merged in 2025-04, with the labels that each got.

#2901 fix(split): add source to battery event
  app/src/split/central.c
Labels: split

#2909 chore(eslint): upgrade to eslint v9 and flat config
  docs/.eslintignore
  docs/.eslintrc.js
  docs/eslint.config.mjs
  docs/package-lock.json
  docs/package.json
  docs/src/theme/prism-include-languages.js
Labels: documentation, chore

#2849 Combo RAM and Kconfig reduction
  app/Kconfig
  app/dts/bindings/zmk,combos.yaml
  app/src/combo.c
  docs/docs/config/combos.md
Labels: refactor, combos

#2926 fix(combos): Restore prompts for two deprecated Kconfigs
  app/Kconfig
Labels: bug, combos

#2928 fix(combos): Properly clean up all old candidates.
  app/src/combo.c
Labels: bug, combos
