Repository zmkfirmware/zmk, pull requests merged in 2025-08, with the labels that each got.

#2900 feat(boards/shields): Add settings for Rpi Pico and add tester_rpi_pico shield
  app/boards/rpi_pico.conf
  app/boards/rpi_pico.overlay
  app/boards/shields/tester_rpi_pico/Kconfig.defconfig
  app/boards/shields/tester_rpi_pico/Kconfig.shield
  app/boards/shields/tester_rpi_pico/tester_rpi_pico-layouts.dtsi
  app/boards/shields/tester_rpi_pico/tester_rpi_pico.keymap
  app/boards/shields/tester_rpi_pico/tester_rpi_pico.overlay
  app/boards/shields/tester_rpi_pico/tester_rpi_pico.zmk.yml
Labels: board, shields

#2715 docs: Add devicetree primer
  docs/docs/config/index.md
  docs/docs/development/devicetree.md
  docs/sidebars.js
Labels: documentation

#3039 docs: Add warning box for clearing settings for splits, generalize troubleshooting procedure
  docs/blog/2023-10-05-zmk-sotf-6.md
  docs/docs/config/settings.md
  docs/docs/config/system.md
  docs/docs/customization.md
  docs/docs/development/hardware-integration/soft-off-setup.mdx
  docs/docs/features/split-keyboards.md
  docs/docs/keymaps/behaviors/backlight.md
  docs/docs/keymaps/behaviors/bluetooth.md
  docs/docs/keymaps/behaviors/outputs.md
  docs/docs/keymaps/behaviors/power.md
  docs/docs/keymaps/behaviors/underglow.md
  docs/docs/troubleshooting/connection-issues.mdx
  docs/docs/user-setup.mdx
Labels: documentation

#3047 fix(core): Generate correct keymap layer names for all builds
  app/include/zmk/keymap.h
  app/src/keymap.c
Labels: bug, core, studio
